#!/usr/bin/env bash
# GENERATED by `ggen sync` from ontology/bcinr.ttl + imports -- DO NOT EDIT.
#
# Fetch pinned oracle sources into oracles/vendor/, which is gitignored. Running
# a program and comparing its output is ordinary use; copying its source into a
# permissively licensed tree is not, and an oracle that lives here stops being
# the independent implementation that made it worth having.
set -euo pipefail
cd "$(dirname "$0")"
mkdir -p vendor

fetch() { # name url commit
    local name=$1 url=$2 commit=$3
    [ -d "vendor/$name/.git" ] || git clone -q "$url" "vendor/$name"
    git -C "vendor/$name" fetch -q --depth 1 origin "$commit" 2>/dev/null \
        || git -C "vendor/$name" fetch -q origin
    git -C "vendor/$name" checkout -q "$commit"
    echo "$name: pinned at $commit"
}

# POWL 2.0 reference implementation (Python, AGPL-3.0)
#   Covers: Algorithm 3: WF-net to POWL 2.0. Runnable today; oracles/differential.py compares conversion verdicts over the shared corpus.
#   Licence: AGPL-3.0: must not be copied into this MIT OR Apache-2.0 tree
fetch powl https://github.com/seanchatmangpt/POWL.git d2bae89b4f3a6375b56225ecfaf5eac3797900dc

# VAL, the PDDL plan validator (C++, BSD-3-Clause)
#   Covers: PDDL plan validity: durative-action semantics, at-end condition timing, and all eleven trajectory-constraint sorts. Source fetched and read; no harness wired yet, so every Found this repository produces is still checked only by the code that produced it.
#   Licence: BSD-3-Clause: must not be copied into this MIT OR Apache-2.0 tree
fetch val https://github.com/KCL-Planning/VAL.git 3c7a1f330bdab0ba28a4762bb45c3f06c27fb6d4

