// This file is generated by tools/cmca-generator/generator.py. DO NOT EDIT.
// Gamma_CMCA schema_version 1. See docs/cmca-rdf/CMCA_ARTIFACT_CONTRACT.md.

use crate::fixed::{NonNegativeFixed, SignedFixed};

pub const N: usize = 8;
pub const F: usize = 10;
pub const K: usize = 4;
pub const Q: usize = 4;
pub const LEAF_FLOOR_N_MAX: usize = 8;

pub const GENERATOR_VERSION: &str = "v2.0.0-mfw";
pub const RDF_INPUT_DIGEST: &str =
    "blake3:9e8c346a943e27085e67d9fc15aa506ad59bb7c6986ff4e44e12e1b7ecf99253";
pub const GENERATOR_SOURCE_DIGEST: &str =
    "blake3:a9e0941502600b62551a9bcecf4220428f6149ecddf22b1b8908e548026fbcf4";
pub const SCHEMA_VERSION: u32 = 1;
pub const FACTOR_ACCESS_FREQUENCY: usize = 0;
pub const FACTOR_ACCESS_FREQUENCY_IRI: &str = "cmca:accessFrequency";
pub const FACTOR_BUSINESS_VALUE: usize = 1;
pub const FACTOR_BUSINESS_VALUE_IRI: &str = "cmca:businessValue";
pub const FACTOR_RECOMPUTATION_COST: usize = 2;
pub const FACTOR_RECOMPUTATION_COST_IRI: &str = "cmca:recomputationCost";
pub const FACTOR_RETRIEVAL_DEMAND: usize = 3;
pub const FACTOR_RETRIEVAL_DEMAND_IRI: &str = "cmca:retrievalDemand";
pub const FACTOR_SCHEDULING_DEMAND: usize = 4;
pub const FACTOR_SCHEDULING_DEMAND_IRI: &str = "cmca:schedulingDemand";
pub const FACTOR_SEARCH_DEMAND: usize = 5;
pub const FACTOR_SEARCH_DEMAND_IRI: &str = "cmca:searchDemand";
pub const FACTOR_STANDING: usize = 6;
pub const FACTOR_STANDING_IRI: &str = "cmca:standing";
pub const FACTOR_VALIDITY: usize = 7;
pub const FACTOR_VALIDITY_IRI: &str = "cmca:validity";
pub const FACTOR_VERIFICATION_COST: usize = 8;
pub const FACTOR_VERIFICATION_COST_IRI: &str = "cmca:verificationCost";
pub const FACTOR_DOWNSTREAM_CONSEQUENCE: usize = 9;
pub const FACTOR_DOWNSTREAM_CONSEQUENCE_IRI: &str = "cmca:downstreamConsequence";
pub const MEASURE_CACHE: usize = 0;
pub const MEASURE_CACHE_IRI: &str = "cmca:MeasureCache";
pub const MEASURE_SEARCH: usize = 1;
pub const MEASURE_SEARCH_IRI: &str = "cmca:MeasureSearch";
pub const MEASURE_RETRIEVAL: usize = 2;
pub const MEASURE_RETRIEVAL_IRI: &str = "cmca:MeasureRetrieval";
pub const MEASURE_SCHEDULING: usize = 3;
pub const MEASURE_SCHEDULING_IRI: &str = "cmca:MeasureScheduling";
pub const LENS_EXPLOITATION: usize = 0;
pub const LENS_EXPLOITATION_IRI: &str = "cmca:LensExploitation";
pub const LENS_PROPORTIONAL: usize = 1;
pub const LENS_PROPORTIONAL_IRI: &str = "cmca:LensProportional";
pub const LENS_COVERAGE: usize = 2;
pub const LENS_COVERAGE_IRI: &str = "cmca:LensCoverage";
pub const LENS_RARE: usize = 3;
pub const LENS_RARE_IRI: &str = "cmca:LensRare";
pub const OBJECT_ARTIFACT__A: usize = 0;
pub const OBJECT_ARTIFACT__A_IRI: &str = "cmca:Artifact_A";
pub const OBJECT_ARTIFACT__B: usize = 1;
pub const OBJECT_ARTIFACT__B_IRI: &str = "cmca:Artifact_B";
pub const OBJECT_OBJ__ACTIVITY: usize = 2;
pub const OBJECT_OBJ__ACTIVITY_IRI: &str = "cmca:Obj_Activity";
pub const OBJECT_OBJ__DEPLOYMENT: usize = 3;
pub const OBJECT_OBJ__DEPLOYMENT_IRI: &str = "cmca:Obj_Deployment";
pub const OBJECT_OBJ__OBLIGATION: usize = 4;
pub const OBJECT_OBJ__OBLIGATION_IRI: &str = "cmca:Obj_Obligation";
pub const OBJECT_OBJ__OUTCOME: usize = 5;
pub const OBJECT_OBJ__OUTCOME_IRI: &str = "cmca:Obj_Outcome";
pub const OBJECT_OBJ__SINGLE: usize = 6;
pub const OBJECT_OBJ__SINGLE_IRI: &str = "cmca:Obj_Single";
pub const OBJECT_OBJ__VALUE: usize = 7;
pub const OBJECT_OBJ__VALUE_IRI: &str = "cmca:Obj_Value";
pub const FORMULA_UNIFORM_LEAF_FLOOR: &str =
    "F_i = 1[i in Leaves] / |Leaves|  (for i in Leaves; F_i = 0 for i not in Leaves)";
pub const FORMULA_UNIFORM_LEAF_FLOOR_Q16_RESIDUAL: &str = "q = floor(65536 / n_leaves); r = 65536 - q * n_leaves; the first r leaves under canonical rank each receive q + 1 raw Q16.16 units, the remaining (n_leaves - r) leaves each receive q raw units; q * n_leaves + r = 65536 exactly (exact conservation, no residual rounding error).";

#[derive(Copy, Clone, Debug)]
pub struct PackedSemanticState {
    pub id: u32,
    pub factors: [NonNegativeFixed; F],
}

#[derive(Copy, Clone, Debug)]
pub struct LensSpec {
    pub id: u32,
    pub q: SignedFixed,
}

pub static ETA: NonNegativeFixed = NonNegativeFixed::from_value_bits(32768); // 0.5

pub static LAMBDA: [[NonNegativeFixed; Q]; K] = [
    [
        NonNegativeFixed::from_value_bits(26214),
        NonNegativeFixed::from_value_bits(19661),
        NonNegativeFixed::from_value_bits(13107),
        NonNegativeFixed::from_value_bits(6554),
    ], // MeasureCache
    [
        NonNegativeFixed::from_value_bits(6554),
        NonNegativeFixed::from_value_bits(13107),
        NonNegativeFixed::from_value_bits(19661),
        NonNegativeFixed::from_value_bits(26214),
    ], // MeasureSearch
    [
        NonNegativeFixed::from_value_bits(16384),
        NonNegativeFixed::from_value_bits(16384),
        NonNegativeFixed::from_value_bits(16384),
        NonNegativeFixed::from_value_bits(16384),
    ], // MeasureRetrieval
    [
        NonNegativeFixed::from_value_bits(32768),
        NonNegativeFixed::from_value_bits(0),
        NonNegativeFixed::from_value_bits(32768),
        NonNegativeFixed::from_value_bits(0),
    ], // MeasureScheduling
];

pub static OBJECT_REGISTRY: [PackedSemanticState; N] = [
    // Artifact_A (cmca:Artifact_A)
    PackedSemanticState {
        id: 0,
        factors: [
            NonNegativeFixed::from_value_bits(32768), // accessFrequency: 0.5
            NonNegativeFixed::from_value_bits(655360), // businessValue: 10.0
            NonNegativeFixed::from_value_bits(58982), // recomputationCost: 0.9
            NonNegativeFixed::from_value_bits(0),     // retrievalDemand: 0.0
            NonNegativeFixed::from_value_bits(0),     // schedulingDemand: 0.0
            NonNegativeFixed::from_value_bits(0),     // searchDemand: 0.0
            NonNegativeFixed::from_value_bits(65536), // standing: 1.0
            NonNegativeFixed::from_value_bits(65536), // validity: 1.0
            NonNegativeFixed::from_value_bits(6554),  // verificationCost: 0.1
            NonNegativeFixed::from_value_bits(655360), // downstreamConsequence: 10.0
        ],
    },
    // Artifact_B (cmca:Artifact_B)
    PackedSemanticState {
        id: 1,
        factors: [
            NonNegativeFixed::from_value_bits(32768), // accessFrequency: 0.5
            NonNegativeFixed::from_value_bits(655360), // businessValue: 10.0
            NonNegativeFixed::from_value_bits(6554),  // recomputationCost: 0.1
            NonNegativeFixed::from_value_bits(0),     // retrievalDemand: 0.0
            NonNegativeFixed::from_value_bits(0),     // schedulingDemand: 0.0
            NonNegativeFixed::from_value_bits(0),     // searchDemand: 0.0
            NonNegativeFixed::from_value_bits(65536), // standing: 1.0
            NonNegativeFixed::from_value_bits(65536), // validity: 1.0
            NonNegativeFixed::from_value_bits(58982), // verificationCost: 0.9
            NonNegativeFixed::from_value_bits(655360), // downstreamConsequence: 10.0
        ],
    },
    // Obj_Activity (cmca:Obj_Activity)
    PackedSemanticState {
        id: 2,
        factors: [
            NonNegativeFixed::from_value_bits(32768), // accessFrequency: 0.5
            NonNegativeFixed::from_value_bits(0),     // businessValue: 0.0
            NonNegativeFixed::from_value_bits(32768), // recomputationCost: 0.5
            NonNegativeFixed::from_value_bits(32768), // retrievalDemand: 0.5
            NonNegativeFixed::from_value_bits(32768), // schedulingDemand: 0.5
            NonNegativeFixed::from_value_bits(32768), // searchDemand: 0.5
            NonNegativeFixed::from_value_bits(65536), // standing: 1.0
            NonNegativeFixed::from_value_bits(65536), // validity: 1.0
            NonNegativeFixed::from_value_bits(32768), // verificationCost: 0.5
            NonNegativeFixed::from_value_bits(65536000), // downstreamConsequence: 1000.0
        ],
    },
    // Obj_Deployment (cmca:Obj_Deployment)
    PackedSemanticState {
        id: 3,
        factors: [
            NonNegativeFixed::from_value_bits(32768), // accessFrequency: 0.5
            NonNegativeFixed::from_value_bits(0),     // businessValue: 0.0
            NonNegativeFixed::from_value_bits(32768), // recomputationCost: 0.5
            NonNegativeFixed::from_value_bits(32768), // retrievalDemand: 0.5
            NonNegativeFixed::from_value_bits(32768), // schedulingDemand: 0.5
            NonNegativeFixed::from_value_bits(32768), // searchDemand: 0.5
            NonNegativeFixed::from_value_bits(65536), // standing: 1.0
            NonNegativeFixed::from_value_bits(65536), // validity: 1.0
            NonNegativeFixed::from_value_bits(32768), // verificationCost: 0.5
            NonNegativeFixed::from_value_bits(65536000), // downstreamConsequence: 1000.0
        ],
    },
    // Obj_Obligation (cmca:Obj_Obligation)
    PackedSemanticState {
        id: 4,
        factors: [
            NonNegativeFixed::from_value_bits(32768), // accessFrequency: 0.5
            NonNegativeFixed::from_value_bits(0),     // businessValue: 0.0
            NonNegativeFixed::from_value_bits(32768), // recomputationCost: 0.5
            NonNegativeFixed::from_value_bits(32768), // retrievalDemand: 0.5
            NonNegativeFixed::from_value_bits(32768), // schedulingDemand: 0.5
            NonNegativeFixed::from_value_bits(32768), // searchDemand: 0.5
            NonNegativeFixed::from_value_bits(65536), // standing: 1.0
            NonNegativeFixed::from_value_bits(65536), // validity: 1.0
            NonNegativeFixed::from_value_bits(32768), // verificationCost: 0.5
            NonNegativeFixed::from_value_bits(65536000), // downstreamConsequence: 1000.0
        ],
    },
    // Obj_Outcome (cmca:Obj_Outcome)
    PackedSemanticState {
        id: 5,
        factors: [
            NonNegativeFixed::from_value_bits(32768), // accessFrequency: 0.5
            NonNegativeFixed::from_value_bits(0),     // businessValue: 0.0
            NonNegativeFixed::from_value_bits(32768), // recomputationCost: 0.5
            NonNegativeFixed::from_value_bits(32768), // retrievalDemand: 0.5
            NonNegativeFixed::from_value_bits(32768), // schedulingDemand: 0.5
            NonNegativeFixed::from_value_bits(32768), // searchDemand: 0.5
            NonNegativeFixed::from_value_bits(65536), // standing: 1.0
            NonNegativeFixed::from_value_bits(65536), // validity: 1.0
            NonNegativeFixed::from_value_bits(32768), // verificationCost: 0.5
            NonNegativeFixed::from_value_bits(65536000), // downstreamConsequence: 1000.0
        ],
    },
    // Obj_Single (cmca:Obj_Single)
    PackedSemanticState {
        id: 6,
        factors: [
            NonNegativeFixed::from_value_bits(52429), // accessFrequency: 0.8
            NonNegativeFixed::from_value_bits(6553600), // businessValue: 100.0
            NonNegativeFixed::from_value_bits(52429), // recomputationCost: 0.8
            NonNegativeFixed::from_value_bits(58982), // retrievalDemand: 0.9
            NonNegativeFixed::from_value_bits(0),     // schedulingDemand: 0.0
            NonNegativeFixed::from_value_bits(6554),  // searchDemand: 0.1
            NonNegativeFixed::from_value_bits(65536), // standing: 1.0
            NonNegativeFixed::from_value_bits(65536), // validity: 1.0
            NonNegativeFixed::from_value_bits(52429), // verificationCost: 0.8
            NonNegativeFixed::from_value_bits(6553600), // downstreamConsequence: 100.0
        ],
    },
    // Obj_Value (cmca:Obj_Value)
    PackedSemanticState {
        id: 7,
        factors: [
            NonNegativeFixed::from_value_bits(32768), // accessFrequency: 0.5
            NonNegativeFixed::from_value_bits(65536000), // businessValue: 1000.0
            NonNegativeFixed::from_value_bits(32768), // recomputationCost: 0.5
            NonNegativeFixed::from_value_bits(32768), // retrievalDemand: 0.5
            NonNegativeFixed::from_value_bits(32768), // schedulingDemand: 0.5
            NonNegativeFixed::from_value_bits(32768), // searchDemand: 0.5
            NonNegativeFixed::from_value_bits(65536), // standing: 1.0
            NonNegativeFixed::from_value_bits(65536), // validity: 1.0
            NonNegativeFixed::from_value_bits(32768), // verificationCost: 0.5
            NonNegativeFixed::from_value_bits(65536000), // downstreamConsequence: 1000.0
        ],
    },
];

pub static LENS_REGISTRY: [LensSpec; Q] = [
    // LensExploitation (cmca:LensExploitation)
    LensSpec {
        id: 0,
        q: SignedFixed::from_value_bits(131072),
    },
    // LensProportional (cmca:LensProportional)
    LensSpec {
        id: 1,
        q: SignedFixed::from_value_bits(65536),
    },
    // LensCoverage (cmca:LensCoverage)
    LensSpec {
        id: 2,
        q: SignedFixed::from_value_bits(0),
    },
    // LensRare (cmca:LensRare)
    LensSpec {
        id: 3,
        q: SignedFixed::from_value_bits(-65536),
    },
];

// Base-q + residual-r Q16.16 uniform leaf-floor projection tables (replaces the
// rounded-reciprocal LEAF_RECIP table). Index i (0-based) corresponds to n_leaves = i + 1.
// Invariant checked at generation time (not emitted as a runtime assert): for every
// n_leaves in [1, LEAF_FLOOR_N_MAX], base_q * n_leaves + residual_r == 65536 exactly.
pub static LEAF_FLOOR_BASE: [u32; LEAF_FLOOR_N_MAX] =
    [65536, 32768, 21845, 16384, 13107, 10922, 9362, 8192];
pub static LEAF_FLOOR_REMAINDER: [u32; LEAF_FLOOR_N_MAX] = [0, 0, 1, 0, 1, 4, 2, 0];

// Macro generation
macro_rules! unroll_n_static {
    ($idx:ident, $body:block) => {
        const $idx: usize = 0;
        $body
        const $idx: usize = 1;
        $body
        const $idx: usize = 2;
        $body
        const $idx: usize = 3;
        $body
        const $idx: usize = 4;
        $body
        const $idx: usize = 5;
        $body
        const $idx: usize = 6;
        $body
        const $idx: usize = 7;
        $body
    };
}
macro_rules! unroll_q_static {
    ($idx:ident, $body:block) => {
        const $idx: usize = 0;
        $body
        const $idx: usize = 1;
        $body
        const $idx: usize = 2;
        $body
        const $idx: usize = 3;
        $body
    };
}
macro_rules! unroll_k_static {
    ($idx:ident, $body:block) => {
        const $idx: usize = 0;
        $body
        const $idx: usize = 1;
        $body
        const $idx: usize = 2;
        $body
        const $idx: usize = 3;
        $body
    };
}
