// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/chains.ttl + ggen/schema/patterns.ttl.
// Regenerate: `ggen sync` (rule `procmine_model`, query chain_models.rq + template
// procmine_model.rs.tera). Joins each ch:ChainStep -> ch:pattern -> w4g:id, ordered by
// (chainName, stepIndex), so each chain's `activities` is its declared process model.

//! The normative process model: each JTBD chain as an ordered activity sequence.
//!
//! A [`ChainModel`] is the *de jure* model in process-mining terms — the prescribed order
//! of activities (pattern ids) that a conforming trace must reproduce. [`CHAIN_MODELS`] is
//! the committed projection of `chains.ttl`, ordered by chain name so the table is stable
//! across regenerations.

/// One JTBD chain expressed as an ordered activity sequence (the declared model order).
///
/// `activities[i]` is the [`crate::ir::PatternId`] raw code of step `i + 1` (the kernel that
/// `ggen` resolved from the chain's `ch:pattern` at that `ch:stepIndex`). `golden` is the
/// chain's `ch:golden` composition digest, reused as a per-chain anchor so a model edit and a
/// composition-oracle edit move together.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct ChainModel {
    /// Stable 1-based chain id (position in [`CHAIN_MODELS`], ordered by chain name).
    pub chain_id: u16,
    /// The chain's snake_case name (matches `ch:name` in `chains.ttl`).
    pub name: &'static str,
    /// The 8 ordered activity (pattern-id) codes — the declared model order.
    pub activities: [u16; 8],
    /// The chain's `ch:golden` FNV-1a composition digest (mirrors the chain test `GOLDEN`).
    pub golden: u64,
}

impl ChainModel {
    /// The declared activity sequence as a slice.
    #[inline]
    #[must_use = "returns the model's activity order; bind or compare it"]
    pub fn activities(&self) -> &[u16] {
        &self.activities
    }
}

/// All 8 JTBD chains, ordered by chain name. The single source of normative model order.
///
/// GENERATED from `chains.ttl`; every `activities` entry is a valid id present in
/// [`crate::patterns::PATTERN_REGISTRY`] (asserted by the module tests).
pub static CHAIN_MODELS: &[ChainModel] = &[
    ChainModel {
        chain_id: 1,
        name: "anticheat_verdict",
        activities: [71, 72, 73, 74, 75, 3, 6, 9],
        golden: 0x3bf04dda41b48d9c,
    },
    ChainModel {
        chain_id: 2,
        name: "audio_cascade",
        activities: [49, 46, 47, 48, 50, 2, 7, 9],
        golden: 0xd0fcd15a8450c3c0,
    },
    ChainModel {
        chain_id: 3,
        name: "combat_hit",
        activities: [1, 5, 14, 3, 15, 71, 9, 20],
        golden: 0xfeeba62f449f2718,
    },
    ChainModel {
        chain_id: 4,
        name: "mp_resync",
        activities: [55, 51, 52, 54, 53, 3, 9, 6],
        golden: 0x0a245f5ba670cb04,
    },
    ChainModel {
        chain_id: 5,
        name: "nav_quest",
        activities: [25, 21, 22, 24, 17, 13, 6, 9],
        golden: 0x33853c6b941518fd,
    },
    ChainModel {
        chain_id: 6,
        name: "procgen_tile",
        activities: [26, 28, 30, 27, 29, 10, 4, 9],
        golden: 0xa0d0718aa4dea29d,
    },
    ChainModel {
        chain_id: 7,
        name: "quality_loop",
        activities: [58, 56, 57, 60, 63, 61, 65, 62],
        golden: 0x962cb513fb562b48,
    },
    ChainModel {
        chain_id: 8,
        name: "shop_purchase",
        activities: [33, 34, 31, 16, 35, 18, 19, 20],
        golden: 0x5dda04bc0681c63e,
    },
];
