files=(
    "hilbert_curve_encode_u32"
    "huffman_decode_table_step"
    "hyperloglog_add_u64"
    "hyperloglog_merge"
    "insertion_sort_branchless_fixed"
    "internet_checksum_u16"
    "inverse_permute_u32x8"
    "is_alphanumeric_simd_u8x16"
    "is_contiguous_mask_u64"
    "is_digit_simd_u8x16"
    "is_finite_fp32_branchless"
    "is_nan_fp32_branchless"
    "is_permutation_branchless"
    "is_prime_u64_branchless"
    "is_sorted_branchless_u32"
    "is_space_simd_u8x16"
    "is_subset_mask_u64"
    "jaro_winkler_branchless"
    "json_find_string_escapes_simd"
    "json_find_structural_simd"
    "k_independent_hash_gen"
    "knuth_hash_u64"
    "lcm_u64_branchless"
    "lcp_array_step_branchless"
    "leaky_relu_u32"
    "leb128_decode_u64"
    "leb128_encode_u64"
    "lerp_sat_u32"
    "lerp_sat_u8"
    "levenshtein_dist_branchless"
    "lex_compare_u8_slices_branchless"
)

for f in "${files[@]}"; do
    echo "Testing $f"
    cargo test -p bcinr-logic --lib "algorithms::${f}::" -- --quiet >/dev/null 2>&1 || echo "$f FAILED"
done
