#![no_std]
#![forbid(unsafe_code)]
#![allow(clippy::needless_range_loop)]

//! # wasm4games
//!
//! A branchless, `no_std`, engine-agnostic *game-pattern foundry*. Game behaviors
//! (input admission, ticks, collision, combat, status, physics, evidence, promotion)
//! are expressed as **bounded byte-class state** transformed by **branchless kernels**
//! that reuse the verified primitives in [`bcinr_logic`]. Every meaningful transition
//! can emit **object-centric evidence** ([`evidence::ocel`]), **runtime span codes**
//! ([`evidence::otel`]), a **receipt chain** ([`evidence::receipt`]), and a
//! **deterministic replay frame** ([`evidence::replay`]).
//!
//! ## Doctrine
//! - Engines project worlds; wasm4games operates patterns; wasm4pm admits evidence.
//! - Kernels are **generated by ggen** from the input surface in `ggen/`; the committed
//!   files under [`patterns`] are the offline source of truth. See the "GGEN-ONLY USER
//!   SURFACE" covenant in the docs.
//! - wasm4pm is *referenced, not vendored*: [`compat`] holds dependency-free mirror types
//!   shaped like `wasm4pm-compat`; the real admission bridge lives in the
//!   workspace-excluded `wasm4games-wasm4pm` crate.

#[cfg(feature = "alloc")]
extern crate alloc;
#[cfg(all(test, feature = "std"))]
extern crate std;

pub mod class;
pub mod compat;
pub mod corpus;
pub mod evidence;
pub mod ir;
pub mod patterns;
pub mod verify;

/// Re-export of the marker trait so downstream code uses a single `Branchless` notion.
pub use bcinr_logic::Branchless;

/// Curated re-exports for ergonomic downstream use.
pub mod prelude {
    pub use crate::class::{status, ByteClass, Status};
    pub use crate::evidence::ocel::{ObjectRefs, OcelEvent};
    pub use crate::evidence::otel::SpanCode;
    pub use crate::evidence::receipt::{ReceiptChain, ReceiptEnvelope};
    pub use crate::evidence::replay::ReplayFrame;
    pub use crate::ir::{
        AdmissionRule, EventKind, LoweringKind, ObjectKind, PatternId, PatternSpec,
    };
    pub use crate::patterns::PATTERN_REGISTRY;
}
