// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (aabb_collision_resolved)
// Regenerate: `ggen sync`. Lowering: Mask.

//! Pattern: AabbCollisionResolved
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Resolve whether two axis-aligned bounding boxes overlap on the separating-axis test,
//! computed branchlessly by AND-ing four [`bcinr_logic::mask::lt_mask_u32`] results.

use bcinr_logic::mask::lt_mask_u32;

/// AabbCollisionResolved kernel. Packed-u64 ABI (each box is 4x u16):
/// - `state` (box A): [min_x, min_y, max_x, max_y] in 16-bit lanes 0..4.
/// - `input` (box B): [min_x, min_y, max_x, max_y] in 16-bit lanes 0..4.
///
/// Returns `1` in bit[0] if the boxes overlap, else `0`.
#[inline]
#[must_use]
pub fn aabb_collision_resolved(state: u64, input: u64) -> u64 {
    let a_min_x = (state & 0xFFFF) as u32;
    let a_min_y = ((state >> 16) & 0xFFFF) as u32;
    let a_max_x = ((state >> 32) & 0xFFFF) as u32;
    let a_max_y = ((state >> 48) & 0xFFFF) as u32;
    let b_min_x = (input & 0xFFFF) as u32;
    let b_min_y = ((input >> 16) & 0xFFFF) as u32;
    let b_max_x = ((input >> 32) & 0xFFFF) as u32;
    let b_max_y = ((input >> 48) & 0xFFFF) as u32;

    let overlap_x = lt_mask_u32(a_min_x, b_max_x) & lt_mask_u32(b_min_x, a_max_x);
    let overlap_y = lt_mask_u32(a_min_y, b_max_y) & lt_mask_u32(b_min_y, a_max_y);
    let overlap = overlap_x & overlap_y;
    (overlap & 1) as u64
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn aabb_collision_resolved_reference(state: u64, input: u64) -> u64 {
        let a_min_x = (state & 0xFFFF) as u32;
        let a_min_y = ((state >> 16) & 0xFFFF) as u32;
        let a_max_x = ((state >> 32) & 0xFFFF) as u32;
        let a_max_y = ((state >> 48) & 0xFFFF) as u32;
        let b_min_x = (input & 0xFFFF) as u32;
        let b_min_y = ((input >> 16) & 0xFFFF) as u32;
        let b_max_x = ((input >> 32) & 0xFFFF) as u32;
        let b_max_y = ((input >> 48) & 0xFFFF) as u32;
        let hit = a_min_x < b_max_x && b_min_x < a_max_x && a_min_y < b_max_y && b_min_y < a_max_y;
        hit as u64
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        aabb_collision_resolved_reference(s, i) ^ 1
    }
    fn mutant_2(s: u64, i: u64) -> u64 {
        aabb_collision_resolved_reference(s, i).wrapping_add(1)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        aabb_collision_resolved_reference(s, i) ^ 0xFF
    }

    fn pack(min_x: u16, min_y: u16, max_x: u16, max_y: u16) -> u64 {
        (min_x as u64) | ((min_y as u64) << 16) | ((max_x as u64) << 32) | ((max_y as u64) << 48)
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(
                aabb_collision_resolved_reference(s, i),
                aabb_collision_resolved(s, i)
            );
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = aabb_collision_resolved_reference(s, i);
            prop_assert!(r != mutant_1(s, i));
        }
        #[test]
        fn cf2(s in any::<u64>(), i in any::<u64>()) {
            let r = aabb_collision_resolved_reference(s, i);
            prop_assert!(r != mutant_2(s, i));
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = aabb_collision_resolved_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // Overlapping boxes.
        let a = pack(0, 0, 10, 10);
        let b = pack(5, 5, 15, 15);
        assert_eq!(aabb_collision_resolved(a, b), 1);
        // Disjoint boxes.
        let c = pack(20, 20, 30, 30);
        assert_eq!(aabb_collision_resolved(a, c), 0);
        // Touching edge (max == min) is not an overlap.
        let d = pack(10, 0, 20, 10);
        assert_eq!(aabb_collision_resolved(a, d), 0);
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_aabb_collision_resolved(c: &mut Criterion) {
        let a = 0x000A_000A_0000_0000u64;
        let b = 0x000F_000F_0005_0005u64;
        c.bench_function("aabb_collision_resolved", |bch| {
            bch.iter(|| black_box(aabb_collision_resolved(black_box(a), black_box(b))))
        });
    }
}

// Hoare-logic Verification Line 1: overlap is the AND of two independent axis tests.
// Hoare-logic Verification Line 2: edge-touching (strict <) yields no collision.
