// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (camera_follow_lerped)
// Regenerate: `ggen sync`. Lowering: Lut.

//! Pattern: CameraFollowLerped
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Fixed-point lerp approximation for camera follow: new_pos = current + (target - current) *
//! alpha / 256. Uses [`bcinr_logic::int::saturating_sub_i64`],
//! [`bcinr_logic::int::saturating_add_i64`], and [`bcinr_logic::fix::clamp_u32`] to avoid
//! overflow and keep the result in the valid u16 range.

use bcinr_logic::fix::clamp_u32;
use bcinr_logic::int::{saturating_add_i64, saturating_sub_i64};

/// CameraFollowLerped kernel. Packed-u64 ABI:
/// - `state`: bits[0..16] = current camera position (u16).
/// - `input`: bits[0..16] = target position, bits[16..24] = alpha (0..255, lerp factor as 1/256).
///
/// Returns: bits[0..16] = new camera position (stepped toward target).
#[inline]
#[must_use]
pub fn camera_follow_lerped(state: u64, input: u64) -> u64 {
    let current = (state & 0xFFFF) as i64;
    let target = (input & 0xFFFF) as i64;
    let alpha = ((input >> 16) & 0xFF) as i64;
    let diff = saturating_sub_i64(target, current);
    let step = (diff * alpha) / 256; // integer division, no branches
    let new_pos = saturating_add_i64(current, step);
    let clamped = clamp_u32(new_pos.max(0) as u32, 0, 0xFFFF);
    (clamped as u64) & 0xFFFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn camera_follow_lerped_reference(state: u64, input: u64) -> u64 {
        let current = (state & 0xFFFF) as i64;
        let target = (input & 0xFFFF) as i64;
        let alpha = ((input >> 16) & 0xFF) as i64;
        let diff = target - current;
        let step = (diff * alpha) / 256;
        let new_pos = (current + step).clamp(0, 0xFFFF);
        (new_pos as u64) & 0xFFFF
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !camera_follow_lerped_reference(s, i)
    }
    fn mutant_2(s: u64, i: u64) -> u64 {
        camera_follow_lerped_reference(s, i).wrapping_add(1)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        camera_follow_lerped_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(camera_follow_lerped_reference(s, i), camera_follow_lerped(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = camera_follow_lerped_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf2(s in any::<u64>(), i in any::<u64>()) {
            let r = camera_follow_lerped_reference(s, i);
            prop_assert!(r != mutant_2(s, i));
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = camera_follow_lerped_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // curr=100, target=200, alpha=128 -> 100 + (100*128/256) = 100+50 = 150
        let s1 = 100u64;
        let i1 = 200u64 | (128u64 << 16);
        assert_eq!(camera_follow_lerped(s1, i1), 150);
        // curr=200, target=100, alpha=128 -> 200 + (-100*128/256) = 200-50 = 150
        let s2 = 200u64;
        let i2 = 100u64 | (128u64 << 16);
        assert_eq!(camera_follow_lerped(s2, i2), 150);
        // curr=100, target=100, alpha=255 -> 100 + 0 = 100
        let s3 = 100u64;
        let i3 = 100u64 | (255u64 << 16);
        assert_eq!(camera_follow_lerped(s3, i3), 100);
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_camera_follow_lerped(c: &mut Criterion) {
        let s = 100u64;
        let i = 200u64 | (128u64 << 16);
        c.bench_function("camera_follow_lerped", |b| {
            b.iter(|| black_box(camera_follow_lerped(black_box(s), black_box(i))))
        });
    }
}

// Hoare-logic Verification Line 1: saturating_sub_i64 and saturating_add_i64 prevent i64 overflow in lerp step.
// Hoare-logic Verification Line 2: clamp_u32 + max(0) guarantee result ∈ [0, 0xFFFF], a valid u16 position.
