// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (capability_flag_evaluated)
// Regenerate: `ggen sync`. Lowering: Bitset.

//! Pattern: CapabilityFlagEvaluated
//!
//! # Branchless Contract
//! **Ensures:** result matches reference oracle for all inputs.
//! **Invariant:** execution path is data-independent (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Test whether a given capability bit is set in a 64-bit capability flags word, and return
//! its rank (how many lower-indexed capabilities are active). Useful for branchless capability
//! gating in engine bridge adapters.

use bcinr_logic::bitset::rank_u64;

/// CapabilityFlagEvaluated kernel. Packed-u64 ABI:
/// - `state`: bits[0..64] = capability flags word (u64).
/// - `input`: bits[0..8] = capability index to test (0..63).
///
/// Returns: bits[0..8] = 1 if capability is set, 0 otherwise;
///          bits[8..16] = rank of capability among lower active capabilities.
#[inline]
#[must_use]
pub fn capability_flag_evaluated(state: u64, input: u64) -> u64 {
    let flags = state;
    let idx = (input & 0x3F) as u32;
    let bit_set = ((flags >> idx) & 1) as u64;
    let rank = rank_u64(flags, idx as usize) as u64;
    bit_set | (rank << 8)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn capability_flag_evaluated_reference(state: u64, input: u64) -> u64 {
        let flags = state;
        let idx = (input & 0x3F) as u32;
        let b = (flags >> idx) & 1;
        let mask = (1u64 << idx).saturating_sub(1);
        let r = (flags & mask).count_ones() as u64;
        b | (r << 8)
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !capability_flag_evaluated_reference(s, i)
    }
    fn mutant_2(s: u64, i: u64) -> u64 {
        capability_flag_evaluated_reference(s, i).wrapping_add(1)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        capability_flag_evaluated_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(capability_flag_evaluated_reference(s, i), capability_flag_evaluated(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = capability_flag_evaluated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf2(s in any::<u64>(), i in any::<u64>()) {
            let r = capability_flag_evaluated_reference(s, i);
            prop_assert!(r != mutant_2(s, i));
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = capability_flag_evaluated_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // flags=0b1100 (bits 2 and 3 set), idx=2 -> bit=1, rank=1 (bit 0 and 1 not set, but bit 2 is set
        // with 1 set bit below idx=2 ... wait: mask=(1<<2)-1=0b11, flags&0b11=0 -> rank=0.
        // Actually flags=0b1100: bit2=1, bit3=1. mask for idx=2 = (1<<2)-1=0b11 -> flags&0b11=0 -> rank=0.
        // Re-check: idx=2, bit at position 2 = (0b1100>>2)&1 = 1. rank = count_ones(flags & 0b11) = 0.
        // So bit=1, rank=0. Expected: bit=1,rank=1 as noted in spec is WRONG for this input.
        // The spec says flags=0b1100/idx=2 -> bit=1,rank=1. That's inconsistent with the definition.
        // rank_u64 counts bits strictly BELOW idx. 0b1100 has no bits set below position 2. rank=0.
        // We match the reference oracle, not the (erroneous) spec description.
        let flags: u64 = 0b1100;
        let out = capability_flag_evaluated(flags, 2);
        assert_eq!(out & 0xFF, 1); // bit 2 is set
        assert_eq!((out >> 8) & 0xFF, capability_flag_evaluated_reference(flags, 2) >> 8 & 0xFF);
        // flags=0b1100, idx=0 -> bit=0, rank=0.
        let out2 = capability_flag_evaluated(0b1100, 0);
        assert_eq!(out2 & 0xFF, 0);
        assert_eq!((out2 >> 8) & 0xFF, 0);
        // flags=u64::MAX, idx=63 -> bit=1, rank=63.
        let out3 = capability_flag_evaluated(u64::MAX, 63);
        assert_eq!(out3 & 0xFF, 1);
        assert_eq!((out3 >> 8) & 0xFF, 63);
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    const S: u64 = 0b1100;
    const I: u64 = 2;
    pub fn bench_capability_flag_evaluated(c: &mut Criterion) {
        c.bench_function("capability_flag_evaluated", |b| {
            b.iter(|| black_box(capability_flag_evaluated(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: rank_u64 counts set bits strictly below idx via a branchless prefix mask.
// Hoare-logic Verification Line 2: idx is clamped to 0..63 via bitmask before shift to prevent UB.
