// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (damage_applied)
// Regenerate: `ggen sync`. Lowering: Saturating.

//! Pattern: DamageApplied
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Apply branchless saturating damage with crit select and an HP floor.

use bcinr_logic::int::saturating_sub_i64;
use bcinr_logic::mask::select_u64;

/// DamageApplied kernel. Packed-u64 ABI:
/// - `state`: bits[0..16] = current HP.
/// - `input`: bits[0..16] = base damage, bit[16] = crit flag.
///
/// Returns new HP in bits[0..16].
#[inline]
#[must_use]
pub fn damage_applied(state: u64, input: u64) -> u64 {
    let hp = (state & 0xFFFF) as i64;
    let dmg = (input & 0xFFFF) as i64;
    let crit_mask = 0u64.wrapping_sub((input >> 16) & 1);
    let dmg_eff = select_u64(crit_mask, (dmg as u64).wrapping_mul(2), dmg as u64) as i64;
    let new_hp = saturating_sub_i64(hp, dmg_eff);
    let floored = new_hp.max(0);
    (floored as u64) & 0xFFFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn damage_applied_reference(state: u64, input: u64) -> u64 {
        let hp = (state & 0xFFFF) as i64;
        let dmg = (input & 0xFFFF) as i64;
        let crit = ((input >> 16) & 1) == 1;
        let d = if crit { dmg * 2 } else { dmg };
        let r = hp - d;
        (if r < 0 { 0 } else { r } as u64) & 0xFFFF
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !damage_applied_reference(s, i)
    }
    fn mutant_2(s: u64, i: u64) -> u64 {
        damage_applied_reference(s, i).wrapping_add(1)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        damage_applied_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(damage_applied_reference(s, i), damage_applied(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = damage_applied_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf2(s in any::<u64>(), i in any::<u64>()) {
            let r = damage_applied_reference(s, i);
            prop_assert!(r != mutant_2(s, i));
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = damage_applied_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        assert_eq!(damage_applied(0, 0), damage_applied_reference(0, 0));
        assert_eq!(
            damage_applied(0xFFFF, 0xFFFF),
            damage_applied_reference(0xFFFF, 0xFFFF)
        );
        assert_eq!(damage_applied(100, 7), damage_applied_reference(100, 7));
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_damage_applied(c: &mut Criterion) {
        c.bench_function("damage_applied", |b| {
            b.iter(|| black_box(damage_applied(black_box(100), black_box(7))))
        });
    }
}

// Hoare-logic Verification Line 1: damage saturates at the HP floor (result >= 0).
// Hoare-logic Verification Line 2: crit doubles base damage via branchless select.
