// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl + ggen/queries/pattern_index.rq.
// Regenerate: `ggen sync`.

//! Generated branchless pattern kernels.
//!
//! GENERATED SURFACE: the modules and the [`PATTERN_REGISTRY`] in this file are produced by
//! `ggen sync` from the input surface in `ggen/` and committed so the offline build never
//! needs ggen. Do not hand-edit generated kernels; edit `ggen/schema/patterns.ttl` and
//! regenerate. See the "GGEN-ONLY USER SURFACE" covenant in the docs.

use crate::class::status;
use crate::ir::{AdmissionRule, EventKind, LoweringKind, ObjectKind, PatternId, PatternSpec};

// --- Kernel modules (ordered by pattern id) -------------------------------------------

pub mod aabb_collision_resolved;
pub mod ai_action_selected;
pub mod damage_applied;
pub mod entity_state_transitioned;
pub mod fixed_tick_advanced;
pub mod input_admitted;
pub mod inventory_item_changed;
pub mod mastery_moment_detected;
pub mod nps_prompt_gated;
pub mod object_spawned;
pub mod ocel_event_linked;
pub mod otel_span_emitted;
pub mod physics_value_rendered;
pub mod projectile_advanced;
pub mod quest_step_advanced;
pub mod receipt_appended;
pub mod replay_frame_recorded;
pub mod semantic_lod_selected;
pub mod share_artifact_generated;
pub mod status_effect_ticked;

// --- Kernel re-exports ----------------------------------------------------------------

pub use aabb_collision_resolved::aabb_collision_resolved;
pub use ai_action_selected::ai_action_selected;
pub use damage_applied::damage_applied;
pub use entity_state_transitioned::entity_state_transitioned;
pub use fixed_tick_advanced::fixed_tick_advanced;
pub use input_admitted::input_admitted;
pub use inventory_item_changed::inventory_item_changed;
pub use mastery_moment_detected::mastery_moment_detected;
pub use nps_prompt_gated::nps_prompt_gated;
pub use object_spawned::object_spawned;
pub use ocel_event_linked::ocel_event_linked;
pub use otel_span_emitted::otel_span_emitted;
pub use physics_value_rendered::physics_value_rendered;
pub use projectile_advanced::projectile_advanced;
pub use quest_step_advanced::quest_step_advanced;
pub use receipt_appended::receipt_appended;
pub use replay_frame_recorded::replay_frame_recorded;
pub use semantic_lod_selected::semantic_lod_selected;
pub use share_artifact_generated::share_artifact_generated;
pub use status_effect_ticked::status_effect_ticked;

// --- Object-kind code map (stable; reused across patterns) ----------------------------

const PLAYER: ObjectKind = ObjectKind {
    code: 0x0001,
    name: "player",
};
const WORLD: ObjectKind = ObjectKind {
    code: 0x0002,
    name: "world",
};
const ENTITY: ObjectKind = ObjectKind {
    code: 0x0003,
    name: "entity",
};
const ENTITY_A: ObjectKind = ObjectKind {
    code: 0x0004,
    name: "entity_a",
};
const ENTITY_B: ObjectKind = ObjectKind {
    code: 0x0005,
    name: "entity_b",
};
const ATTACKER: ObjectKind = ObjectKind {
    code: 0x0006,
    name: "attacker",
};
const TARGET: ObjectKind = ObjectKind {
    code: 0x0007,
    name: "target",
};
const RECEIPT_CHAIN: ObjectKind = ObjectKind {
    code: 0x0008,
    name: "receipt_chain",
};
const EVENT: ObjectKind = ObjectKind {
    code: 0x0009,
    name: "event",
};
const OBJECT: ObjectKind = ObjectKind {
    code: 0x000A,
    name: "object",
};
const SPAN: ObjectKind = ObjectKind {
    code: 0x000B,
    name: "span",
};
const FRAME: ObjectKind = ObjectKind {
    code: 0x000C,
    name: "frame",
};
const QUANTITY: ObjectKind = ObjectKind {
    code: 0x000D,
    name: "quantity",
};
const HUD_WIDGET: ObjectKind = ObjectKind {
    code: 0x000E,
    name: "hud_widget",
};
const PROJECTILE: ObjectKind = ObjectKind {
    code: 0x000F,
    name: "projectile",
};
const SESSION: ObjectKind = ObjectKind {
    code: 0x0010,
    name: "session",
};
const ARTIFACT: ObjectKind = ObjectKind {
    code: 0x0011,
    name: "artifact",
};
const PROMPT: ObjectKind = ObjectKind {
    code: 0x0012,
    name: "prompt",
};
const AGENT: ObjectKind = ObjectKind {
    code: 0x0013,
    name: "agent",
};
const ITEM: ObjectKind = ObjectKind {
    code: 0x0014,
    name: "item",
};
const QUEST: ObjectKind = ObjectKind {
    code: 0x0015,
    name: "quest",
};

// --- Per-pattern object slices --------------------------------------------------------

const OBJ_INPUT_ADMITTED: &[ObjectKind] = &[PLAYER];
const OBJ_FIXED_TICK_ADVANCED: &[ObjectKind] = &[WORLD];
const OBJ_ENTITY_STATE_TRANSITIONED: &[ObjectKind] = &[ENTITY];
const OBJ_OBJECT_SPAWNED: &[ObjectKind] = &[ENTITY];
const OBJ_AABB_COLLISION_RESOLVED: &[ObjectKind] = &[ENTITY_A, ENTITY_B];
const OBJ_OCEL_EVENT_LINKED: &[ObjectKind] = &[EVENT, OBJECT];
const OBJ_OTEL_SPAN_EMITTED: &[ObjectKind] = &[SPAN];
const OBJ_REPLAY_FRAME_RECORDED: &[ObjectKind] = &[FRAME];
const OBJ_RECEIPT_APPENDED: &[ObjectKind] = &[RECEIPT_CHAIN];
const OBJ_PHYSICS_VALUE_RENDERED: &[ObjectKind] = &[QUANTITY];
const OBJ_SEMANTIC_LOD_SELECTED: &[ObjectKind] = &[HUD_WIDGET];
const OBJ_PROJECTILE_ADVANCED: &[ObjectKind] = &[PROJECTILE];
const OBJ_AI_ACTION_SELECTED: &[ObjectKind] = &[AGENT];
const OBJ_DAMAGE_APPLIED: &[ObjectKind] = &[ATTACKER, TARGET];
const OBJ_STATUS_EFFECT_TICKED: &[ObjectKind] = &[TARGET];
const OBJ_INVENTORY_ITEM_CHANGED: &[ObjectKind] = &[PLAYER, ITEM];
const OBJ_QUEST_STEP_ADVANCED: &[ObjectKind] = &[PLAYER, QUEST];
const OBJ_MASTERY_MOMENT_DETECTED: &[ObjectKind] = &[PLAYER, SESSION];
const OBJ_SHARE_ARTIFACT_GENERATED: &[ObjectKind] = &[PLAYER, ARTIFACT];
const OBJ_NPS_PROMPT_GATED: &[ObjectKind] = &[PLAYER, PROMPT];

/// The standard admission contract: admissible at [`status::ADMITTED`], refused with
/// [`status::REFUSED`].
const STD_ADMISSION: AdmissionRule = AdmissionRule {
    required_status: status::ADMITTED,
    refusal_status: status::REFUSED,
};

/// The catalog of all generated patterns as data. Iterated by [`crate::verify`].
pub static PATTERN_REGISTRY: &[PatternSpec] = &[
    PatternSpec {
        id: PatternId(1),
        name: "input_admitted",
        lowering: LoweringKind::Mask,
        state_card: status::COUNT,
        event: EventKind {
            code: 0x0002,
            name: "InputAdmitted",
        },
        objects: OBJ_INPUT_ADMITTED,
        admission: STD_ADMISSION,
        otel_span: 0x0002,
    },
    PatternSpec {
        id: PatternId(2),
        name: "fixed_tick_advanced",
        lowering: LoweringKind::Saturating,
        state_card: 64,
        event: EventKind {
            code: 0x0001,
            name: "FixedTickAdvanced",
        },
        objects: OBJ_FIXED_TICK_ADVANCED,
        admission: STD_ADMISSION,
        otel_span: 0x0001,
    },
    PatternSpec {
        id: PatternId(3),
        name: "entity_state_transitioned",
        lowering: LoweringKind::Dfa,
        state_card: 4,
        event: EventKind {
            code: 0x0010,
            name: "EntityStateTransitioned",
        },
        objects: OBJ_ENTITY_STATE_TRANSITIONED,
        admission: STD_ADMISSION,
        otel_span: 0x0010,
    },
    PatternSpec {
        id: PatternId(4),
        name: "object_spawned",
        lowering: LoweringKind::Lut,
        state_card: 6,
        event: EventKind {
            code: 0x0012,
            name: "ObjectSpawned",
        },
        objects: OBJ_OBJECT_SPAWNED,
        admission: STD_ADMISSION,
        otel_span: 0x0012,
    },
    PatternSpec {
        id: PatternId(5),
        name: "aabb_collision_resolved",
        lowering: LoweringKind::Mask,
        state_card: 2,
        event: EventKind {
            code: 0x0011,
            name: "AabbCollisionResolved",
        },
        objects: OBJ_AABB_COLLISION_RESOLVED,
        admission: STD_ADMISSION,
        otel_span: 0x0011,
    },
    PatternSpec {
        id: PatternId(6),
        name: "ocel_event_linked",
        lowering: LoweringKind::Mask,
        state_card: 32,
        event: EventKind {
            code: 0x0021,
            name: "OcelEventLinked",
        },
        objects: OBJ_OCEL_EVENT_LINKED,
        admission: STD_ADMISSION,
        otel_span: 0x0021,
    },
    PatternSpec {
        id: PatternId(7),
        name: "otel_span_emitted",
        lowering: LoweringKind::Lut,
        state_card: 8,
        event: EventKind {
            code: 0x0022,
            name: "OtelSpanEmitted",
        },
        objects: OBJ_OTEL_SPAN_EMITTED,
        admission: STD_ADMISSION,
        otel_span: 0x0022,
    },
    PatternSpec {
        id: PatternId(8),
        name: "replay_frame_recorded",
        lowering: LoweringKind::Receipt,
        state_card: 64,
        event: EventKind {
            code: 0x0023,
            name: "ReplayFrameRecorded",
        },
        objects: OBJ_REPLAY_FRAME_RECORDED,
        admission: STD_ADMISSION,
        otel_span: 0x0023,
    },
    PatternSpec {
        id: PatternId(9),
        name: "receipt_appended",
        lowering: LoweringKind::Receipt,
        state_card: 64,
        event: EventKind {
            code: 0x0020,
            name: "ReceiptAppended",
        },
        objects: OBJ_RECEIPT_APPENDED,
        admission: STD_ADMISSION,
        otel_span: 0x0003,
    },
    PatternSpec {
        id: PatternId(10),
        name: "physics_value_rendered",
        lowering: LoweringKind::Saturating,
        state_card: 32,
        event: EventKind {
            code: 0x0030,
            name: "PhysicsValueRendered",
        },
        objects: OBJ_PHYSICS_VALUE_RENDERED,
        admission: STD_ADMISSION,
        otel_span: 0x0030,
    },
    PatternSpec {
        id: PatternId(11),
        name: "semantic_lod_selected",
        lowering: LoweringKind::Lut,
        state_card: 7,
        event: EventKind {
            code: 0x0031,
            name: "SemanticLodSelected",
        },
        objects: OBJ_SEMANTIC_LOD_SELECTED,
        admission: STD_ADMISSION,
        otel_span: 0x0031,
    },
    PatternSpec {
        id: PatternId(12),
        name: "projectile_advanced",
        lowering: LoweringKind::Saturating,
        state_card: 32,
        event: EventKind {
            code: 0x0032,
            name: "ProjectileAdvanced",
        },
        objects: OBJ_PROJECTILE_ADVANCED,
        admission: STD_ADMISSION,
        otel_span: 0x0032,
    },
    PatternSpec {
        id: PatternId(13),
        name: "ai_action_selected",
        lowering: LoweringKind::Mask,
        state_card: 4,
        event: EventKind {
            code: 0x0040,
            name: "AiActionSelected",
        },
        objects: OBJ_AI_ACTION_SELECTED,
        admission: STD_ADMISSION,
        otel_span: 0x0040,
    },
    PatternSpec {
        id: PatternId(14),
        name: "damage_applied",
        lowering: LoweringKind::Saturating,
        state_card: 16,
        event: EventKind {
            code: 0x0042,
            name: "DamageApplied",
        },
        objects: OBJ_DAMAGE_APPLIED,
        admission: STD_ADMISSION,
        otel_span: 0x0042,
    },
    PatternSpec {
        id: PatternId(15),
        name: "status_effect_ticked",
        lowering: LoweringKind::Bitset,
        state_card: 16,
        event: EventKind {
            code: 0x0043,
            name: "StatusEffectTicked",
        },
        objects: OBJ_STATUS_EFFECT_TICKED,
        admission: STD_ADMISSION,
        otel_span: 0x0043,
    },
    PatternSpec {
        id: PatternId(16),
        name: "inventory_item_changed",
        lowering: LoweringKind::Bitset,
        state_card: 32,
        event: EventKind {
            code: 0x0044,
            name: "InventoryItemChanged",
        },
        objects: OBJ_INVENTORY_ITEM_CHANGED,
        admission: STD_ADMISSION,
        otel_span: 0x0044,
    },
    PatternSpec {
        id: PatternId(17),
        name: "quest_step_advanced",
        lowering: LoweringKind::Dfa,
        state_card: 5,
        event: EventKind {
            code: 0x0045,
            name: "QuestStepAdvanced",
        },
        objects: OBJ_QUEST_STEP_ADVANCED,
        admission: STD_ADMISSION,
        otel_span: 0x0045,
    },
    PatternSpec {
        id: PatternId(18),
        name: "mastery_moment_detected",
        lowering: LoweringKind::Bitset,
        state_card: 32,
        event: EventKind {
            code: 0x0050,
            name: "MasteryMomentDetected",
        },
        objects: OBJ_MASTERY_MOMENT_DETECTED,
        admission: STD_ADMISSION,
        otel_span: 0x0050,
    },
    PatternSpec {
        id: PatternId(19),
        name: "share_artifact_generated",
        lowering: LoweringKind::Receipt,
        state_card: 64,
        event: EventKind {
            code: 0x0051,
            name: "ShareArtifactGenerated",
        },
        objects: OBJ_SHARE_ARTIFACT_GENERATED,
        admission: STD_ADMISSION,
        otel_span: 0x0051,
    },
    PatternSpec {
        id: PatternId(20),
        name: "nps_prompt_gated",
        lowering: LoweringKind::Mask,
        state_card: status::COUNT,
        event: EventKind {
            code: 0x0052,
            name: "NpsPromptGated",
        },
        objects: OBJ_NPS_PROMPT_GATED,
        admission: STD_ADMISSION,
        otel_span: 0x0052,
    },
];
