// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (noise_value_sampled)
// Regenerate: `ggen sync`. Lowering: Receipt.

//! Pattern: NoiseValueSampled
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Deterministic hash-based noise — fold (seed, x, y) through a
//! [`bcinr_logic::patterns::integrity_receipt::DeterministicSubstrateReceipt`] to produce a
//! bounded noise value in [0, 255].

use bcinr_logic::patterns::integrity_receipt::DeterministicSubstrateReceipt;

/// NoiseValueSampled kernel. Packed-u64 ABI:
/// - `state`: bits[0..32] = seed.
/// - `input`: bits[0..16] = x coordinate, bits[16..32] = y coordinate.
///
/// Returns: bits[0..8] = noise value in 0..=255.
#[inline]
#[must_use]
pub fn noise_value_sampled(state: u64, input: u64) -> u64 {
    let seed = state & 0xFFFF_FFFF;
    let x = (input & 0xFFFF) as u64;
    let y = ((input >> 16) & 0xFFFF) as u64;
    let mut r = DeterministicSubstrateReceipt::new();
    r.record(seed, x, y);
    r.finalize() & 0xFF
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn noise_value_sampled_reference(state: u64, input: u64) -> u64 {
        use bcinr_logic::patterns::integrity_receipt::DeterministicSubstrateReceipt;
        let seed = state & 0xFFFF_FFFF;
        let x = (input & 0xFFFF) as u64;
        let y = ((input >> 16) & 0xFFFF) as u64;
        let mut r = DeterministicSubstrateReceipt::new();
        r.record(seed, x, y);
        r.finalize() & 0xFF
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !noise_value_sampled_reference(s, i)
    }
    fn mutant_2(s: u64, i: u64) -> u64 {
        noise_value_sampled_reference(s, i).wrapping_add(1)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        noise_value_sampled_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(noise_value_sampled_reference(s, i), noise_value_sampled(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = noise_value_sampled_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf2(s in any::<u64>(), i in any::<u64>()) {
            let r = noise_value_sampled_reference(s, i);
            prop_assert!(r != mutant_2(s, i));
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = noise_value_sampled_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // (seed=0, x=0, y=0) produces a deterministic value.
        let v0 = noise_value_sampled(0, 0);
        assert_eq!(v0, noise_value_sampled_reference(0, 0));
        // Different coordinates produce a different result.
        let v1 = noise_value_sampled(1, 1 | (1 << 16));
        assert_ne!(v0, v1);
        // Same inputs produce the same result (determinism).
        assert_eq!(noise_value_sampled(0, 0), noise_value_sampled(0, 0));
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_noise_value_sampled(c: &mut Criterion) {
        c.bench_function("noise_value_sampled", |b| {
            b.iter(|| black_box(noise_value_sampled(black_box(42), black_box(7 | (3 << 16)))))
        });
    }
}

// Hoare-logic Verification Line 1: the FNV-1a receipt fold is a pure function of (seed, x, y).
// Hoare-logic Verification Line 2: masking by 0xFF constrains the result to [0, 255].
