// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (semantic_lod_selected)
// Regenerate: `ggen sync`. Lowering: Lut.

//! Pattern: SemanticLodSelected
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Select a semantic level-of-detail bucket for a HUD widget from a distance value:
//! quantize distance with [`bcinr_logic::fix::bucketize_u32`], then read the LOD tier from a
//! bounded table (7 tiers).

use bcinr_logic::fix::{bucketize_u32, clamp_u32};

/// LOD tier table (lower tier index = more detail). 7 semantic levels.
#[rustfmt::skip]
const LOD_LUT: [u16; 7] = [0, 1, 2, 3, 4, 5, 6];

/// SemanticLodSelected kernel. Packed-u64 ABI:
/// - `state`: unused (reserved for a camera id).
/// - `input`: bits[0..32] = distance, bits[32..48] = step (distance units per tier),
///   defaulting to `64` when zero.
///
/// Returns the selected LOD tier in bits[0..16].
#[inline]
#[must_use]
pub fn semantic_lod_selected(state: u64, input: u64) -> u64 {
    let _ = state;
    let dist = (input & 0xFFFF_FFFF) as u32;
    let raw_step = ((input >> 32) & 0xFFFF) as u32;
    // step defaults to 64 when zero, branchlessly.
    let step = raw_step.wrapping_add(64u32.wrapping_mul((raw_step == 0) as u32));
    let bucket = bucketize_u32(dist, step) / step;
    let tier = clamp_u32(bucket, 0, (LOD_LUT.len() - 1) as u32) as usize;
    LOD_LUT[tier] as u64
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn semantic_lod_selected_reference(_state: u64, input: u64) -> u64 {
        let dist = (input & 0xFFFF_FFFF) as u32;
        let mut step = ((input >> 32) & 0xFFFF) as u32;
        if step == 0 {
            step = 64;
        }
        let bucket = (dist / step).min((LOD_LUT.len() - 1) as u32) as usize;
        LOD_LUT[bucket] as u64
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !semantic_lod_selected_reference(s, i)
    }
    fn mutant_2(s: u64, i: u64) -> u64 {
        semantic_lod_selected_reference(s, i).wrapping_add(1)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        semantic_lod_selected_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in any::<u64>(), i in any::<u64>()) {
            prop_assert_eq!(semantic_lod_selected_reference(s, i), semantic_lod_selected(s, i));
        }
        #[test]
        fn cf1(s in any::<u64>(), i in any::<u64>()) {
            let r = semantic_lod_selected_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf2(s in any::<u64>(), i in any::<u64>()) {
            let r = semantic_lod_selected_reference(s, i);
            prop_assert!(r != mutant_2(s, i));
        }
        #[test]
        fn cf3(s in any::<u64>(), i in any::<u64>()) {
            let r = semantic_lod_selected_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // distance 0 -> tier 0 (default step 64).
        assert_eq!(semantic_lod_selected(0, 0), 0);
        // distance 130, step 64 -> bucket 2.
        assert_eq!(semantic_lod_selected(0, 130 | (64u64 << 32)), 2);
        // far distance clamps to last tier.
        assert_eq!(semantic_lod_selected(0, 0xFFFF_FFFF), 6);
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    pub fn bench_semantic_lod_selected(c: &mut Criterion) {
        let input = 130u64 | (64u64 << 32);
        c.bench_function("semantic_lod_selected", |b| {
            b.iter(|| black_box(semantic_lod_selected(black_box(0), black_box(input))))
        });
    }
}

// Hoare-logic Verification Line 1: the LOD tier is clamped into the table's bounds.
// Hoare-logic Verification Line 2: a zero step defaults to a fixed unit, avoiding div-by-zero.
