// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/patterns.ttl (sync_state_admitted)
// Regenerate: `ggen sync`. Lowering: Dfa.

//! Pattern: SyncStateAdmitted
//!
//! # Branchless Contract
//! **Ensures:** result matches the reference oracle for all inputs.
//! **Invariant:** execution path is independent of input data values (Branchless).
//!
//! # Timing contract
//! - T0 primitive budget: ~1 ns. T1 aggregate: <= 200 ns. Max heap allocations: 0.
//!
//! Advance a synchronization FSM via branchless DFA table lookup.
//! States: UNSYNCED=0, SYNCING=1, SYNCED=2, DRIFTED=3, LOST=4 (5 states).
//! Symbols: START_SYNC=0, ACK=1, DRIFT=2, TIMEOUT=3, RESYNC=4 (5 symbols).

use bcinr_logic::dfa::dfa_advance;

const UNSYNCED: usize = 0;
const SYNCING: usize = 1;
const SYNCED: usize = 2;
const DRIFTED: usize = 3;
const LOST: usize = 4;

// Transition table: SYNC_TABLE[state * 5 + symbol] = next_state
// Rows: UNSYNCED=0, SYNCING=1, SYNCED=2, DRIFTED=3, LOST=4
// Cols: START_SYNC=0, ACK=1, DRIFT=2, TIMEOUT=3, RESYNC=4
#[rustfmt::skip]
static SYNC_TABLE: [usize; 25] = [
    // UNSYNCED: START_SYNC->SYNCING, ACK->UNSYNCED, DRIFT->UNSYNCED, TIMEOUT->UNSYNCED, RESYNC->SYNCING
    SYNCING,  UNSYNCED, UNSYNCED, UNSYNCED, SYNCING,
    // SYNCING:  START_SYNC->SYNCING, ACK->SYNCED,   DRIFT->DRIFTED,  TIMEOUT->LOST,     RESYNC->SYNCING
    SYNCING,  SYNCED,   DRIFTED,  LOST,     SYNCING,
    // SYNCED:   START_SYNC->SYNCED,  ACK->SYNCED,   DRIFT->DRIFTED,  TIMEOUT->LOST,     RESYNC->SYNCING
    SYNCED,   SYNCED,   DRIFTED,  LOST,     SYNCING,
    // DRIFTED:  START_SYNC->SYNCING, ACK->SYNCED,   DRIFT->DRIFTED,  TIMEOUT->LOST,     RESYNC->SYNCING
    SYNCING,  SYNCED,   DRIFTED,  LOST,     SYNCING,
    // LOST:     START_SYNC->SYNCING, ACK->LOST,     DRIFT->LOST,     TIMEOUT->LOST,     RESYNC->SYNCING
    SYNCING,  LOST,     LOST,     LOST,     SYNCING,
];

/// SyncStateAdmitted kernel. Packed-u64 ABI:
/// - `state`: bits[0..8] = current sync state (0=UNSYNCED, 1=SYNCING, 2=SYNCED, 3=DRIFTED, 4=LOST).
/// - `input`: bits[0..8] = symbol (0=START_SYNC, 1=ACK, 2=DRIFT, 3=TIMEOUT, 4=RESYNC).
///
/// Returns: bits[0..8] = next sync state.
#[inline]
#[must_use]
pub fn sync_state_admitted(state: u64, input: u64) -> u64 {
    let current = (state & 0xFF) as usize;
    let symbol = (input & 0xFF) as u8;
    dfa_advance(current, symbol, &SYNC_TABLE, 5) as u64
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn sync_state_admitted_reference(state: u64, input: u64) -> u64 {
        let s = ((state & 0xFF) as usize).min(4);
        let sym = ((input & 0xFF) as usize).min(4);
        let next = match (s, sym) {
            // UNSYNCED
            (0, 0) => 1, // START_SYNC -> SYNCING
            (0, 1) => 0, // ACK -> UNSYNCED
            (0, 2) => 0, // DRIFT -> UNSYNCED
            (0, 3) => 0, // TIMEOUT -> UNSYNCED
            (0, 4) => 1, // RESYNC -> SYNCING
            // SYNCING
            (1, 0) => 1, // START_SYNC -> SYNCING
            (1, 1) => 2, // ACK -> SYNCED
            (1, 2) => 3, // DRIFT -> DRIFTED
            (1, 3) => 4, // TIMEOUT -> LOST
            (1, 4) => 1, // RESYNC -> SYNCING
            // SYNCED
            (2, 0) => 2, // START_SYNC -> SYNCED
            (2, 1) => 2, // ACK -> SYNCED
            (2, 2) => 3, // DRIFT -> DRIFTED
            (2, 3) => 4, // TIMEOUT -> LOST
            (2, 4) => 1, // RESYNC -> SYNCING
            // DRIFTED
            (3, 0) => 1, // START_SYNC -> SYNCING
            (3, 1) => 2, // ACK -> SYNCED
            (3, 2) => 3, // DRIFT -> DRIFTED
            (3, 3) => 4, // TIMEOUT -> LOST
            (3, 4) => 1, // RESYNC -> SYNCING
            // LOST
            (4, 0) => 1, // START_SYNC -> SYNCING
            (4, 1) => 4, // ACK -> LOST
            (4, 2) => 4, // DRIFT -> LOST
            (4, 3) => 4, // TIMEOUT -> LOST
            (4, 4) => 1, // RESYNC -> SYNCING
            _ => s,
        };
        next as u64
    }
    fn mutant_1(s: u64, i: u64) -> u64 {
        !sync_state_admitted_reference(s, i)
    }
    fn mutant_2(s: u64, i: u64) -> u64 {
        sync_state_admitted_reference(s, i).wrapping_add(1)
    }
    fn mutant_3(s: u64, i: u64) -> u64 {
        sync_state_admitted_reference(s, i) ^ 0xFFFF
    }

    proptest! {
        #[test]
        fn equivalence(s in 0u64..5, i in 0u64..5) {
            prop_assert_eq!(sync_state_admitted_reference(s, i), sync_state_admitted(s, i));
        }
        #[test]
        fn cf1(s in 0u64..5, i in 0u64..5) {
            let r = sync_state_admitted_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_1(s, i)); }
        }
        #[test]
        fn cf2(s in 0u64..5, i in 0u64..5) {
            let r = sync_state_admitted_reference(s, i);
            prop_assert!(r != mutant_2(s, i));
        }
        #[test]
        fn cf3(s in 0u64..5, i in 0u64..5) {
            let r = sync_state_admitted_reference(s, i);
            if r != 0 { prop_assert!(r != mutant_3(s, i)); }
        }
    }

    #[test]
    fn boundaries() {
        // UNSYNCED(0) + START_SYNC(0) -> SYNCING(1)
        assert_eq!(sync_state_admitted(0, 0), 1);
        // SYNCING(1) + ACK(1) -> SYNCED(2)
        assert_eq!(sync_state_admitted(1, 1), 2);
        // SYNCED(2) + TIMEOUT(3) -> LOST(4)
        assert_eq!(sync_state_admitted(2, 3), 4);
    }
}

#[cfg(feature = "bench")]
pub mod bench {
    use super::*;
    use criterion::{black_box, Criterion};
    const S: u64 = 0;
    const I: u64 = 0;
    pub fn bench_sync_state_admitted(c: &mut Criterion) {
        c.bench_function("sync_state_admitted", |b| {
            b.iter(|| black_box(sync_state_admitted(black_box(S), black_box(I))))
        });
    }
}

// Hoare-logic Verification Line 1: dfa_advance indexes SYNC_TABLE at state*5+symbol with bounds-safe masking — no conditional branch in the hot path.
// Hoare-logic Verification Line 2: transition table encodes all 25 (state, symbol) pairs; LOST absorbs ACK/DRIFT/TIMEOUT and RESYNC/START_SYNC escape to SYNCING.
