// GENERATED by `ggen sync` from ontology/bcinr.ttl + imports -- DO NOT EDIT.
//
// One test per refusal variant the graph claims is reachable. Each runs the
// witness recorded against that variant and asserts the refusal it actually
// produces.
//
// Why this file and not a comment: `bc:falsifier` used to be prose. Prose
// cannot fail, so when the soundness gate started catching the
// `IrreducibleFragment` witness first, the recorded falsifier silently stopped
// being true and nothing noticed. A generated test is the same claim in a
// medium where it can be wrong out loud.
//
// A variant with no witness does not appear here. It is not thereby exempt:
// `ontology/shapes.ttl` refuses to admit a refusal case that carries neither a
// witness nor a written argument for why none exists, so absence from this
// file is always accompanied by a recorded reason rather than by silence.

/// `CascadeRefusal::LengthMismatch` -- parent and mass vectors disagree in length.
#[test]
fn falsifier_cascaderefusal_lengthmismatch() {
    use bcinr_cmca::cascade::{consequence_mass, CascadeTree};
    use bcinr_cmca::fixed::NonNegativeFixed;
    let m = |v: f64| NonNegativeFixed::from_bits((v * 65536.0) as u32);

    let observed = CascadeTree::new(vec![None], vec![m(1.0), m(1.0)]).map(|_| ());
    assert!(
        matches!(observed, Err(bcinr_cmca::cascade::CascadeRefusal::LengthMismatch { .. })),
        "the graph declares CascadeRefusal::LengthMismatch reachable by this witness, but it produced {:?}",
        observed
    );
}

/// `CascadeRefusal::ParentOutOfRange` -- A parent index addresses a node that does not exist.
#[test]
fn falsifier_cascaderefusal_parentoutofrange() {
    use bcinr_cmca::cascade::{consequence_mass, CascadeTree};
    use bcinr_cmca::fixed::NonNegativeFixed;
    let m = |v: f64| NonNegativeFixed::from_bits((v * 65536.0) as u32);

    let observed = CascadeTree::new(vec![None, Some(9)], vec![m(1.0), m(1.0)]).map(|_| ());
    assert!(
        matches!(observed, Err(bcinr_cmca::cascade::CascadeRefusal::ParentOutOfRange { .. })),
        "the graph declares CascadeRefusal::ParentOutOfRange reachable by this witness, but it produced {:?}",
        observed
    );
}

/// `CascadeRefusal::Cyclic` -- The parent relation contains a cycle, so no hierarchy exists.
#[test]
fn falsifier_cascaderefusal_cyclic() {
    use bcinr_cmca::cascade::{consequence_mass, CascadeTree};
    use bcinr_cmca::fixed::NonNegativeFixed;
    let m = |v: f64| NonNegativeFixed::from_bits((v * 65536.0) as u32);
    let t = CascadeTree::new(vec![None, Some(2), Some(1)], vec![m(1.0), m(1.0), m(1.0)]).unwrap();
    let observed = consequence_mass(&t, &[2]).map(|_| ());
    assert!(
        matches!(
            observed,
            Err(bcinr_cmca::cascade::CascadeRefusal::Cyclic { .. })
        ),
        "the graph declares CascadeRefusal::Cyclic reachable by this witness, but it produced {:?}",
        observed
    );
}

/// `CascadeRefusal::NoRoot` -- Every node has a parent, so there is nowhere for flow to enter.
#[test]
fn falsifier_cascaderefusal_noroot() {
    use bcinr_cmca::cascade::{consequence_mass, CascadeTree};
    use bcinr_cmca::fixed::NonNegativeFixed;
    let m = |v: f64| NonNegativeFixed::from_bits((v * 65536.0) as u32);
    let t = CascadeTree::new(vec![Some(0)], vec![m(1.0)]).unwrap();
    let observed = consequence_mass(&t, &[2]).map(|_| ());
    assert!(
        matches!(observed, Err(bcinr_cmca::cascade::CascadeRefusal::NoRoot)),
        "the graph declares CascadeRefusal::NoRoot reachable by this witness, but it produced {:?}",
        observed
    );
}

/// `CascadeRefusal::ExponentOutOfRange` -- A lens exponent exceeds the admitted magnitude.
#[test]
fn falsifier_cascaderefusal_exponentoutofrange() {
    use bcinr_cmca::cascade::{consequence_mass, CascadeTree};
    use bcinr_cmca::fixed::NonNegativeFixed;
    let m = |v: f64| NonNegativeFixed::from_bits((v * 65536.0) as u32);
    let t = CascadeTree::new(vec![None, Some(0), Some(0)], vec![m(1.0), m(1.0), m(1.0)]).unwrap();
    let observed = consequence_mass(&t, &[999]).map(|_| ());
    assert!(
        matches!(observed, Err(bcinr_cmca::cascade::CascadeRefusal::ExponentOutOfRange { .. })),
        "the graph declares CascadeRefusal::ExponentOutOfRange reachable by this witness, but it produced {:?}",
        observed
    );
}

/// `CascadeRefusal::DegenerateSiblingSet` -- All sibling escort weights are zero, so the normalizing sum vanishes. Fires only when ALL underflow; the mixed case is the dangerous one and does not refuse.
#[test]
fn falsifier_cascaderefusal_degeneratesiblingset() {
    use bcinr_cmca::cascade::{consequence_mass, CascadeTree};
    use bcinr_cmca::fixed::NonNegativeFixed;
    let m = |v: f64| NonNegativeFixed::from_bits((v * 65536.0) as u32);
    let t = CascadeTree::new(vec![None, Some(0), Some(0)], vec![m(1.0), m(0.0), m(0.0)]).unwrap();
    let observed = consequence_mass(&t, &[2]).map(|_| ());
    assert!(
        matches!(observed, Err(bcinr_cmca::cascade::CascadeRefusal::DegenerateSiblingSet { .. })),
        "the graph declares CascadeRefusal::DegenerateSiblingSet reachable by this witness, but it produced {:?}",
        observed
    );
}

/// `CascadeRefusal::ZeroMassUnderNegativeLens` -- m^q for m = 0 and q < 0 is undefined, not large.
#[test]
fn falsifier_cascaderefusal_zeromassundernegativelens() {
    use bcinr_cmca::cascade::{consequence_mass, CascadeTree};
    use bcinr_cmca::fixed::NonNegativeFixed;
    let m = |v: f64| NonNegativeFixed::from_bits((v * 65536.0) as u32);
    let t = CascadeTree::new(vec![None, Some(0), Some(0)], vec![m(1.0), m(0.0), m(1.0)]).unwrap();
    let observed = consequence_mass(&t, &[-2]).map(|_| ());
    assert!(
        matches!(observed, Err(bcinr_cmca::cascade::CascadeRefusal::ZeroMassUnderNegativeLens { .. })),
        "the graph declares CascadeRefusal::ZeroMassUnderNegativeLens reachable by this witness, but it produced {:?}",
        observed
    );
}

/// `CascadeRefusal::NumericFault` -- A Q16.16 operation saturated or divided by zero; read off the value's error channel, with the stage named.
#[test]
fn falsifier_cascaderefusal_numericfault() {
    use bcinr_cmca::cascade::{consequence_mass, CascadeTree};
    use bcinr_cmca::fixed::NonNegativeFixed;
    let m = |v: f64| NonNegativeFixed::from_bits((v * 65536.0) as u32);
    let t = CascadeTree::new(
        vec![None, Some(0), Some(0)],
        vec![m(1.0), m(1000.0), m(1000.0)],
    )
    .unwrap();
    let observed = consequence_mass(&t, &[16]).map(|_| ());
    assert!(
        matches!(observed, Err(bcinr_cmca::cascade::CascadeRefusal::NumericFault { .. })),
        "the graph declares CascadeRefusal::NumericFault reachable by this witness, but it produced {:?}",
        observed
    );
}

/// `CascadeRefusal::EscortUnderflow` -- m^q collapsed to zero from a non-zero mass: unrepresentable, not negligible. Detected structurally because saturating_mul flags overflow but not underflow.
#[test]
fn falsifier_cascaderefusal_escortunderflow() {
    use bcinr_cmca::cascade::{consequence_mass, CascadeTree};
    use bcinr_cmca::fixed::NonNegativeFixed;
    let m = |v: f64| NonNegativeFixed::from_bits((v * 65536.0) as u32);
    let t = CascadeTree::new(
        vec![None, Some(0), Some(0)],
        vec![m(1.0), m(0.001), m(900.0)],
    )
    .unwrap();
    let observed = consequence_mass(&t, &[16]).map(|_| ());
    assert!(
        matches!(observed, Err(bcinr_cmca::cascade::CascadeRefusal::EscortUnderflow { .. })),
        "the graph declares CascadeRefusal::EscortUnderflow reachable by this witness, but it produced {:?}",
        observed
    );
}

/// `RefusalReason::IrreducibleFragment` -- Our partitioner found no base case and no valid partition at this level -- Algorithm 3 line 25's FallThrough. It does NOT assert that no POWL structure exists: see bc:referenceDivergence.
#[test]
fn falsifier_refusalreason_irreduciblefragment() {
    use bcinr_powl::wf_net::WfNet;
    use bcinr_powl::wf_to_powl::{convert, convert_and_verify, convert_with_budget};
    let s = |x: &str| x.to_string();
    let net = WfNet::new(
        ["i", "a", "b", "c", "d", "e", "o"].map(s),
        [
            ("t0", None),
            ("t1", Some(s("A"))),
            ("t2", Some(s("B"))),
            ("t3", Some(s("C"))),
            ("t4", None),
            ("t5", None),
        ]
        .map(|(t, l)| (s(t), l)),
        [
            ("i", "t0"),
            ("a", "t1"),
            ("b", "t2"),
            ("a", "t3"),
            ("b", "t3"),
            ("c", "t4"),
            ("d", "t4"),
            ("e", "t5"),
        ]
        .map(|(p, t)| (s(p), s(t))),
        [
            ("t0", "a"),
            ("t0", "b"),
            ("t1", "c"),
            ("t2", "d"),
            ("t3", "e"),
            ("t4", "o"),
            ("t5", "o"),
        ]
        .map(|(t, p)| (s(t), s(p))),
        "i",
        "o",
    )
    .unwrap();
    let observed = convert(&net).map(|_| ());
    assert!(
        matches!(observed, Err(bcinr_powl::wf_to_powl::Refusal { reason: bcinr_powl::wf_to_powl::RefusalReason::IrreducibleFragment { .. }, .. })),
        "the graph declares RefusalReason::IrreducibleFragment reachable by this witness, but it produced {:?}",
        observed
    );
}

/// `RefusalReason::BudgetExhausted` -- The bounded recursion budget ran out before termination.
#[test]
fn falsifier_refusalreason_budgetexhausted() {
    use bcinr_powl::wf_net::WfNet;
    use bcinr_powl::wf_to_powl::{convert, convert_and_verify, convert_with_budget};
    let s = |x: &str| x.to_string();
    let net = WfNet::new(
        ["i", "m", "o"].map(s),
        [("t1", Some(s("A"))), ("t2", Some(s("B")))].map(|(t, l)| (s(t), l)),
        [("i", "t1"), ("m", "t2")].map(|(p, t)| (s(p), s(t))),
        [("t1", "m"), ("t2", "o")].map(|(t, p)| (s(t), s(p))),
        "i",
        "o",
    )
    .unwrap();
    let observed = convert_with_budget(&net, 0).map(|_| ());
    assert!(
        matches!(observed, Err(bcinr_powl::wf_to_powl::Refusal { reason: bcinr_powl::wf_to_powl::RefusalReason::BudgetExhausted { .. }, .. })),
        "the graph declares RefusalReason::BudgetExhausted reachable by this witness, but it produced {:?}",
        observed
    );
}

/// `RefusalReason::VacuousLanguageBound` -- A bound of 0 compares two empty sets. Both enumerators return the empty language there, so they agree vacuously -- independence of implementation does not imply independence of failure mode.
#[test]
fn falsifier_refusalreason_vacuouslanguagebound() {
    use bcinr_powl::wf_net::WfNet;
    use bcinr_powl::wf_to_powl::{convert, convert_and_verify, convert_with_budget};
    let s = |x: &str| x.to_string();
    let net = WfNet::new(
        ["i", "m", "o"].map(s),
        [("t1", Some(s("A"))), ("t2", Some(s("B")))].map(|(t, l)| (s(t), l)),
        [("i", "t1"), ("m", "t2")].map(|(p, t)| (s(p), s(t))),
        [("t1", "m"), ("t2", "o")].map(|(t, p)| (s(t), s(p))),
        "i",
        "o",
    )
    .unwrap();
    let observed = convert_and_verify(&net, 64, 0).map(|_| ());
    assert!(
        matches!(observed, Err(bcinr_powl::wf_to_powl::Refusal { reason: bcinr_powl::wf_to_powl::RefusalReason::VacuousLanguageBound, .. })),
        "the graph declares RefusalReason::VacuousLanguageBound reachable by this witness, but it produced {:?}",
        observed
    );
}

/// `RefusalReason::NotSafe` -- Some reachable marking carries more than one token in a place. Lemmas 5.1-5.4 assume a safe net, so Algorithm 3 would return a model with no proof attached.
#[test]
fn falsifier_refusalreason_notsafe() {
    use bcinr_powl::wf_net::WfNet;
    use bcinr_powl::wf_to_powl::{convert, convert_and_verify, convert_with_budget};
    let s = |x: &str| x.to_string();
    let net = WfNet::new(
        ["i", "a", "b", "c", "o"].map(s),
        [("t1", None), ("t2", None), ("t3", None), ("t4", None)].map(|(t, l)| (s(t), l)),
        [("i", "t1"), ("a", "t2"), ("b", "t3"), ("c", "t4")].map(|(p, t)| (s(p), s(t))),
        [
            ("t1", "a"),
            ("t1", "b"),
            ("t2", "c"),
            ("t3", "c"),
            ("t4", "o"),
        ]
        .map(|(t, p)| (s(t), s(p))),
        "i",
        "o",
    )
    .unwrap();
    let observed = convert(&net).map(|_| ());
    assert!(
        matches!(
            observed,
            Err(bcinr_powl::wf_to_powl::Refusal {
                reason: bcinr_powl::wf_to_powl::RefusalReason::NotSafe { .. },
                ..
            })
        ),
        "the graph declares RefusalReason::NotSafe reachable by this witness, but it produced {:?}",
        observed
    );
}

/// `RefusalReason::NotSound` -- At least one of van der Aalst's three clauses fails: option-to-complete, proper completion, no dead transitions.
#[test]
fn falsifier_refusalreason_notsound() {
    use bcinr_powl::wf_net::WfNet;
    use bcinr_powl::wf_to_powl::{convert, convert_and_verify, convert_with_budget};
    let s = |x: &str| x.to_string();
    let net = WfNet::new(
        ["i", "a", "b", "o"].map(s),
        [("t1", None), ("t2", None), ("t3", None)].map(|(t, l)| (s(t), l)),
        [("i", "t1"), ("a", "t2"), ("a", "t3"), ("b", "t3")].map(|(p, t)| (s(p), s(t))),
        [("t1", "a"), ("t1", "b"), ("t2", "o"), ("t3", "o")].map(|(t, p)| (s(t), s(p))),
        "i",
        "o",
    )
    .unwrap();
    let observed = convert(&net).map(|_| ());
    assert!(
        matches!(observed, Err(bcinr_powl::wf_to_powl::Refusal { reason: bcinr_powl::wf_to_powl::RefusalReason::NotSound { .. }, .. })),
        "the graph declares RefusalReason::NotSound reachable by this witness, but it produced {:?}",
        observed
    );
}
