// GENERATED by `ggen sync` from ontology/graph.ttl -- DO NOT EDIT.
//
// Numeric profile and policy constants. Each carries its provenance: either a
// derivation from a stated rule, or an explicit POLICY marker with an owner.
// No constant here is presented as following from the mathematics unless it
// does.

/// POLICY (owner: bcinr-cmca). UNDERIVED. 0.22 permits a 22 percentage-point disagreement on a normalized allocation share, which is not a tolerance so much as an absence of one. It was chosen to make the fixed-vs-f64 comparison pass, not derived from the numeric profile. The principled replacement is to classify each generated case as inside or outside the executable envelope and compare outcomes rather than values: inside, assert agreement to an error bound derived from ESCORT_DYNAMIC_RANGE_LIMIT; outside, assert NumericRangeExceeded. Until that lands this number is a placeholder and must be labelled as one.
pub const DIFFERENTIAL_TOLERANCE: f64 = 0.22;

/// DERIVED. Derived from the fractional width. The escort kernel is max-shift stabilised -- exp2(q*log2(m_i) - max_j(q*log2(m_j))) -- so the largest weight is exactly 1.0 and overflow is structurally impossible. The binding constraint is the SPREAD: a sibling more than 2^-16 below the maximum underflows to zero. So the representable region is defined by max_j(q*log2(m_j)) - min_j(q*log2(m_j)) < 16, a property of the sibling SET, not of an individual (q, m) pair.
pub const ESCORT_DYNAMIC_RANGE_LIMIT: i32 = 16;

/// POLICY (owner: bcinr-powl::language). UNDERIVED, and load-bearing. The termination argument holds for any finite value, so 2 is a free choice -- but powl2_language IS the bounded-agreement oracle, so this constant silently sets how strong that check is. A larger value enumerates strictly more traces and therefore checks strictly more.
pub const MAX_CYCLE_UNROLL: usize = 2;

/// POLICY (owner: bcinr-cmca::cascade). UNDERIVED, and inconsistent with the allocator. Any value >= 2 satisfies the stated rationale of bounding the repeated-multiplication loop. allocator.rs:1452 independently admits q in [-2, 2]; cascade.rs admits |q| <= 16. Two implementations claiming the same measure accept domains differing by a factor of 8.
pub const MAX_LENS_MAGNITUDE: u32 = 16;

/// DERIVED. Definitional: the representation is Q16.16.
pub const Q16_16_FRACTIONAL_BITS: u32 = 16;
