// GENERATED by `ggen sync` from ontology/bcinr.ttl + imports -- DO NOT EDIT.
//
// Numeric-profile constants. Values marked DERIVED follow the admitted profile;
// policy constants are explicitly named as policy and never promoted to a
// mathematical theorem.

/// DERIVED. Q16.16 has sixteen fractional bits.
pub const Q16_16_FRACTIONAL_BITS: u32 = 16;

/// DERIVED. Maximum admitted normalized escort-exponent spread before a
/// positive sibling weight becomes unrepresentable.
pub const ESCORT_DYNAMIC_RANGE_LIMIT: i32 = 16;

/// DERIVED from the admitted CMCA mathematical lens domain `q ∈ [-2,2]`.
pub const MAX_LENS_MAGNITUDE: u32 = 2;

/// DERIVED comparison component for the fixed-bit log2/exp2 composition.
pub const TRANSCENDENTAL_MAX_ERROR_ULPS: u32 = 4;

/// DERIVED conservative upper bound on value-affecting fixed-point operations
/// on one output path of the bounded N=8,K=4,Q=4 allocator.
pub const ALLOCATION_ERROR_OPERATION_BUDGET: u32 = 1024;

/// POLICY (owner: bcinr-powl::language). This controls bounded enumeration
/// strength only; it never establishes complete-language equivalence.
pub const MAX_CYCLE_UNROLL: usize = 2;
