//! Rust projections of the bcinr admitted semantic graph.
//!
//! Everything in this crate is generated by `ggen sync` from
//! `ontology/graph.ttl`. Do not hand-edit; edit the graph and regenerate.
//!
//! The point is not code reuse. A semantic fact is declared once and every
//! structural representation of it is manufactured, so two representations
//! cannot silently disagree. Where a projection meets an executable type, the
//! generated match has no `_` arm, making drift a compile error.

/// Every closed taxonomy in the system, from one graph and one template.
pub mod taxonomy;

/// The POWL 2.0 model taxonomy with its paper citations, tier and arity
/// bounds, plus the `classify` tripwire against the live `Powl2Model`.
pub mod powl2_case;
