// GENERATED by `ggen sync` from ontology/bcinr.ttl -- DO NOT EDIT.
//
// Presentation only. Every value below is substituted verbatim from a query
// row; this template has no conditionals and makes no decisions. Neutral facts
// live in the ontology; the mapping from those facts to Rust tokens lives in
// queries/powl2-cases.rq.
#![allow(clippy::match_like_matches_macro)]

use bcinr_powl::powl2::Powl2Model;

/// Which constructor of the research object a variant is.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ConstructorTier {
    /// A primitive constructor of the research object itself.
    PaperCore,
    /// Not primitive in the paper. Carries a `derived_from` target.
    ExecutionSuperset,
}

/// A citation into the source of record, resolved from the graph.
///
/// Number and title are projected together, so a refusal or doc comment cannot
/// cite a result that does not exist.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PaperResult {
    pub number: &'static str,
    pub title: &'static str,
}

/// One variant of [`Powl2Model`], as an admitted fact.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Powl2Case {
    /// A labelled transition. Def 3.7's base constructor.
    Activity,
    /// A tau transition: structurally present, contributing no label to the language.
    Silent,
    /// Total order over submodels. Derived: equivalent to a PartialOrder whose edge set is {(i, i+1)}.
    Sequence,
    /// Submodels under a strict partial order over child indices (Def 3.7), interleaved by the order-preserving shuffle of Def 3.8.
    PartialOrder,
    /// A choice graph over submodels (Def 3.6). Its start and finish nodes are ARTIFICIAL: Def 3.6 fixes N = X union {start, finish} with start, finish NOT IN X, and excludes them from the execution sequence.
    ChoiceGraph,
    /// Bounded loop. Derived: a choice-graph cycle, but bounded. An unbounded paper cycle would enlarge the language, so normalization to paper core REFUSES rather than widening it.
    DoRedo,
}

impl Powl2Case {
    /// Every case, in declared order.
    pub const ALL: &'static [Self] = &[
        Self::Activity,
        Self::Silent,
        Self::Sequence,
        Self::PartialOrder,
        Self::ChoiceGraph,
        Self::DoRedo,
    ];

    /// The variant's name as written in the graph.
    pub fn name(&self) -> &'static str {
        match self {
            Self::Activity => "Activity",
            Self::Silent => "Silent",
            Self::Sequence => "Sequence",
            Self::PartialOrder => "PartialOrder",
            Self::ChoiceGraph => "ChoiceGraph",
            Self::DoRedo => "DoRedo",
        }
    }

    /// Paper core, or an execution-oriented encoding on top of it.
    pub fn tier(&self) -> ConstructorTier {
        match self {
            Self::Activity => ConstructorTier::PaperCore,
            Self::Silent => ConstructorTier::PaperCore,
            Self::Sequence => ConstructorTier::ExecutionSuperset,
            Self::PartialOrder => ConstructorTier::PaperCore,
            Self::ChoiceGraph => ConstructorTier::PaperCore,
            Self::DoRedo => ConstructorTier::ExecutionSuperset,
        }
    }

    /// The paper-core constructor this one normalizes to, if it is derived.
    pub fn derived_from(&self) -> Option<Self> {
        match self {
            Self::Activity => None,
            Self::Silent => None,
            Self::Sequence => Some(Self::PartialOrder),
            Self::PartialOrder => None,
            Self::ChoiceGraph => None,
            Self::DoRedo => Some(Self::ChoiceGraph),
        }
    }

    /// How this case relates to its paper-core target, or why it refuses.
    pub fn normalization_note(&self) -> Option<&'static str> {
        match self {
            Self::Activity => None,
            Self::Silent => None,
            Self::Sequence => Some("Sequence(c_0..c_k) == PartialOrder { children: c_0..c_k, edges: {(i, i+1)} }"),
            Self::PartialOrder => None,
            Self::ChoiceGraph => None,
            Self::DoRedo => Some("REFUSES: max_redos has no counterpart in an unbounded paper choice-graph cycle."),
        }
    }

    /// Minimum child count required by the definition (Def 3.7's `n >= 2`).
    pub fn arity_lower_bound(&self) -> Option<usize> {
        match self {
            Self::Activity => None,
            Self::Silent => None,
            Self::Sequence => None,
            Self::PartialOrder => Some(2),
            Self::ChoiceGraph => Some(2),
            Self::DoRedo => None,
        }
    }

    /// The numbered result that defines this case.
    pub fn paper_definition(&self) -> Option<PaperResult> {
        match self {
            Self::Activity => Some(PaperResult { number: "3.7", title: "POWL Model" }),
            Self::Silent => Some(PaperResult { number: "3.7", title: "POWL Model" }),
            Self::Sequence => None,
            Self::PartialOrder => Some(PaperResult { number: "3.7", title: "POWL Model" }),
            Self::ChoiceGraph => Some(PaperResult { number: "3.6", title: "Choice Graph" }),
            Self::DoRedo => None,
        }
    }
}

/// Classify a live model.
///
/// The tripwire: no `_` arm, so a variant added to [`Powl2Model`] without a
/// matching `bc:TaxonCase` in the graph -- or a case added to the graph with
/// no variant -- fails to compile.
pub fn classify(model: &Powl2Model) -> Powl2Case {
    match model {
        Powl2Model::Activity(..) => Powl2Case::Activity,
        Powl2Model::Silent => Powl2Case::Silent,
        Powl2Model::Sequence(..) => Powl2Case::Sequence,
        Powl2Model::PartialOrder { .. } => Powl2Case::PartialOrder,
        Powl2Model::ChoiceGraph { .. } => Powl2Case::ChoiceGraph,
        Powl2Model::DoRedo { .. } => Powl2Case::DoRedo,
    }
}
