// GENERATED by `ggen sync` from ontology/bcinr.ttl + imports -- DO NOT EDIT.
//
// Every closed taxonomy in the bcinr system, projected from one graph by one
// template. Presentation only: the `is_first` / `is_last` flags that open and
// close each enum are computed in queries/taxonomy-cases.rq, not decided here.
//
// A variant set declared here is the single admitted fact. Adding a case to
// the graph changes this file; every exhaustive elimination built on it then
// fails to compile until the new case is handled.


/// Conditions under which the multifractal cascade has no correct answer. Each is a real condition, not a degradation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum CascadeRefusal {
    /// parent and mass vectors disagree in length.
    LengthMismatch,
    /// A parent index addresses a node that does not exist.
    ParentOutOfRange,
    /// The parent relation contains a cycle, so no hierarchy exists.
    Cyclic,
    /// Every node has a parent, so there is nowhere for flow to enter.
    NoRoot,
    /// A lens exponent exceeds the admitted magnitude.
    ExponentOutOfRange,
    /// All sibling escort weights are zero, so the normalizing sum vanishes. Fires only when ALL underflow; the mixed case is the dangerous one and does not refuse.
    DegenerateSiblingSet,
    /// The flat path has no representable subtree-leaf weights.
    DegenerateSubtreeLeaves,
    /// m^q for m = 0 and q < 0 is undefined, not large.
    ZeroMassUnderNegativeLens,
    /// A Q16.16 operation saturated or divided by zero; read off the value's error channel, with the stage named.
    NumericFault,
    /// m^q collapsed to zero from a non-zero mass: unrepresentable, not negligible. Detected structurally because saturating_mul flags overflow but not underflow.
    EscortUnderflow,
}

impl CascadeRefusal {
    /// Every case, in declared order.
    pub const ALL: &'static [Self] = &[
        Self::LengthMismatch,
        Self::ParentOutOfRange,
        Self::Cyclic,
        Self::NoRoot,
        Self::ExponentOutOfRange,
        Self::DegenerateSiblingSet,
        Self::DegenerateSubtreeLeaves,
        Self::ZeroMassUnderNegativeLens,
        Self::NumericFault,
        Self::EscortUnderflow,
    ];

    /// The case's name as written in the graph.
    pub fn name(&self) -> &'static str {
        match self {
            Self::LengthMismatch => "LengthMismatch",
            Self::ParentOutOfRange => "ParentOutOfRange",
            Self::Cyclic => "Cyclic",
            Self::NoRoot => "NoRoot",
            Self::ExponentOutOfRange => "ExponentOutOfRange",
            Self::DegenerateSiblingSet => "DegenerateSiblingSet",
            Self::DegenerateSubtreeLeaves => "DegenerateSubtreeLeaves",
            Self::ZeroMassUnderNegativeLens => "ZeroMassUnderNegativeLens",
            Self::NumericFault => "NumericFault",
            Self::EscortUnderflow => "EscortUnderflow",
        }
    }

    /// The case's documented meaning, from the graph.
    pub fn doc(&self) -> &'static str {
        match self {
            Self::LengthMismatch => "parent and mass vectors disagree in length.",
            Self::ParentOutOfRange => "A parent index addresses a node that does not exist.",
            Self::Cyclic => "The parent relation contains a cycle, so no hierarchy exists.",
            Self::NoRoot => "Every node has a parent, so there is nowhere for flow to enter.",
            Self::ExponentOutOfRange => "A lens exponent exceeds the admitted magnitude.",
            Self::DegenerateSiblingSet => "All sibling escort weights are zero, so the normalizing sum vanishes. Fires only when ALL underflow; the mixed case is the dangerous one and does not refuse.",
            Self::DegenerateSubtreeLeaves => "The flat path has no representable subtree-leaf weights.",
            Self::ZeroMassUnderNegativeLens => "m^q for m = 0 and q < 0 is undefined, not large.",
            Self::NumericFault => "A Q16.16 operation saturated or divided by zero; read off the value's error channel, with the stage named.",
            Self::EscortUnderflow => "m^q collapsed to zero from a non-zero mass: unrepresentable, not negligible. Detected structurally because saturating_mul flags overflow but not underflow.",
        }
    }
}
/// How much standing a claim has. Axiom-cleanliness is necessary, not sufficient: it cannot distinguish a proved theorem from a vacuous one.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum FormalStanding {
    /// Kernel-checked, sorry-free, axioms within the trusted set, and non-vacuity witnessed.
    Proven,
    /// Defined in Lean but not proven to have the properties a caller might assume.
    Stated,
    /// Typechecks and constrains nothing. `exists d, f 0 = d` holds of every f. Audits identically to a real theorem.
    Vacuous,
    /// A bare `def : Prop` with no proof attempted; the open goal its own authors name as such.
    Conjectural,
    /// A countermodel exists.
    Refuted,
    /// No proof and no formalized representation exists at all.
    Blocked,
}

impl FormalStanding {
    /// Every case, in declared order.
    pub const ALL: &'static [Self] = &[
        Self::Proven,
        Self::Stated,
        Self::Vacuous,
        Self::Conjectural,
        Self::Refuted,
        Self::Blocked,
    ];

    /// The case's name as written in the graph.
    pub fn name(&self) -> &'static str {
        match self {
            Self::Proven => "Proven",
            Self::Stated => "Stated",
            Self::Vacuous => "Vacuous",
            Self::Conjectural => "Conjectural",
            Self::Refuted => "Refuted",
            Self::Blocked => "Blocked",
        }
    }

    /// The case's documented meaning, from the graph.
    pub fn doc(&self) -> &'static str {
        match self {
            Self::Proven => "Kernel-checked, sorry-free, axioms within the trusted set, and non-vacuity witnessed.",
            Self::Stated => "Defined in Lean but not proven to have the properties a caller might assume.",
            Self::Vacuous => "Typechecks and constrains nothing. `exists d, f 0 = d` holds of every f. Audits identically to a real theorem.",
            Self::Conjectural => "A bare `def : Prop` with no proof attempted; the open goal its own authors name as such.",
            Self::Refuted => "A countermodel exists.",
            Self::Blocked => "No proof and no formalized representation exists at all.",
        }
    }
}
/// The six effect forms PDDL 3.1 admits. An effect kind that cannot be represented downstream must refuse, never be dropped.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum PddlEffect {
    /// Add a ground atom to the state.
    Add,
    /// Delete a ground atom from the state.
    Del,
    /// Assign/increase/decrease/scale a numeric fluent.
    Numeric,
    /// An effect scoped to at-start / at-end / over-all.
    Timed,
    /// A quantified effect over a typed domain.
    Forall,
    /// A conditional effect. Two actions conflicting only through a `when` are classified independent if this form is dropped.
    When,
}

impl PddlEffect {
    /// Every case, in declared order.
    pub const ALL: &'static [Self] = &[
        Self::Add,
        Self::Del,
        Self::Numeric,
        Self::Timed,
        Self::Forall,
        Self::When,
    ];

    /// The case's name as written in the graph.
    pub fn name(&self) -> &'static str {
        match self {
            Self::Add => "Add",
            Self::Del => "Del",
            Self::Numeric => "Numeric",
            Self::Timed => "Timed",
            Self::Forall => "Forall",
            Self::When => "When",
        }
    }

    /// The case's documented meaning, from the graph.
    pub fn doc(&self) -> &'static str {
        match self {
            Self::Add => "Add a ground atom to the state.",
            Self::Del => "Delete a ground atom from the state.",
            Self::Numeric => "Assign/increase/decrease/scale a numeric fluent.",
            Self::Timed => "An effect scoped to at-start / at-end / over-all.",
            Self::Forall => "A quantified effect over a typed domain.",
            Self::When => "A conditional effect. Two actions conflicting only through a `when` are classified independent if this form is dropped.",
        }
    }
}
/// One recursive POWL 2.0 model. Paper-core constructors are Def 3.7's transition / partial order / choice graph; Sequence, XOR and Do/Redo are derived encodings, not primitives.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Powl2Model {
    /// A labelled transition. Def 3.7's base constructor.
    Activity,
    /// A tau transition: structurally present, contributing no label to the language.
    Silent,
    /// Total order over submodels. Derived: equivalent to a PartialOrder whose edge set is {(i, i+1)}.
    Sequence,
    /// Submodels under a strict partial order over child indices (Def 3.7), interleaved by the order-preserving shuffle of Def 3.8.
    PartialOrder,
    /// A choice graph over submodels (Def 3.6). Its start and finish nodes are ARTIFICIAL: Def 3.6 fixes N = X union {start, finish} with start, finish NOT IN X, and excludes them from the execution sequence.
    ChoiceGraph,
    /// Bounded loop. Derived: a choice-graph cycle, but bounded. An unbounded paper cycle would enlarge the language, so normalization to paper core REFUSES rather than widening it.
    DoRedo,
}

impl Powl2Model {
    /// Every case, in declared order.
    pub const ALL: &'static [Self] = &[
        Self::Activity,
        Self::Silent,
        Self::Sequence,
        Self::PartialOrder,
        Self::ChoiceGraph,
        Self::DoRedo,
    ];

    /// The case's name as written in the graph.
    pub fn name(&self) -> &'static str {
        match self {
            Self::Activity => "Activity",
            Self::Silent => "Silent",
            Self::Sequence => "Sequence",
            Self::PartialOrder => "PartialOrder",
            Self::ChoiceGraph => "ChoiceGraph",
            Self::DoRedo => "DoRedo",
        }
    }

    /// The case's documented meaning, from the graph.
    pub fn doc(&self) -> &'static str {
        match self {
            Self::Activity => "A labelled transition. Def 3.7's base constructor.",
            Self::Silent => "A tau transition: structurally present, contributing no label to the language.",
            Self::Sequence => "Total order over submodels. Derived: equivalent to a PartialOrder whose edge set is {(i, i+1)}.",
            Self::PartialOrder => "Submodels under a strict partial order over child indices (Def 3.7), interleaved by the order-preserving shuffle of Def 3.8.",
            Self::ChoiceGraph => "A choice graph over submodels (Def 3.6). Its start and finish nodes are ARTIFICIAL: Def 3.6 fixes N = X union {start, finish} with start, finish NOT IN X, and excludes them from the execution sequence.",
            Self::DoRedo => "Bounded loop. Derived: a choice-graph cycle, but bounded. An unbounded paper cycle would enlarge the language, so normalization to paper core REFUSES rather than widening it.",
        }
    }
}
/// Why Algorithm 3 declined a net. Each names the obligation actually checked -- not a paper result it does not discharge.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum RefusalReason {
    /// No base case and no valid partition -- Algorithm 3 line 25's FallThrough.
    IrreducibleFragment,
    /// The bounded recursion budget ran out before termination.
    BudgetExhausted,
    /// The two independently-computed languages disagreed at the checked bound. NOT Theorem 5.5, which quantifies over the whole language.
    BoundedLanguageAgreementFailed,
    /// A projection produced a sub-net failing WfNet::new -- algorithm-internal, surfaced as a refusal rather than a panic.
    InternalNetConstruction,
    /// A bound of 0 compares two empty sets. Both enumerators return the empty language there, so they agree vacuously -- independence of implementation does not imply independence of failure mode.
    VacuousLanguageBound,
    /// The model has no language-preserving WF-net image -- e.g. a bounded DoRedo, which an unbounded net cycle would widen.
    NotRecomposable,
    /// Some reachable marking carries more than one token in a place. Lemmas 5.1-5.4 assume a safe net, so Algorithm 3 would return a model with no proof attached.
    NotSafe,
    /// At least one of van der Aalst's three clauses fails: option-to-complete, proper completion, no dead transitions.
    NotSound,
    /// The reachability graph exceeded MAX_REACHABLE_MARKINGS before the token game terminated. Undecided, not decided favourably.
    SoundnessUndecided,
}

impl RefusalReason {
    /// Every case, in declared order.
    pub const ALL: &'static [Self] = &[
        Self::IrreducibleFragment,
        Self::BudgetExhausted,
        Self::BoundedLanguageAgreementFailed,
        Self::InternalNetConstruction,
        Self::VacuousLanguageBound,
        Self::NotRecomposable,
        Self::NotSafe,
        Self::NotSound,
        Self::SoundnessUndecided,
    ];

    /// The case's name as written in the graph.
    pub fn name(&self) -> &'static str {
        match self {
            Self::IrreducibleFragment => "IrreducibleFragment",
            Self::BudgetExhausted => "BudgetExhausted",
            Self::BoundedLanguageAgreementFailed => "BoundedLanguageAgreementFailed",
            Self::InternalNetConstruction => "InternalNetConstruction",
            Self::VacuousLanguageBound => "VacuousLanguageBound",
            Self::NotRecomposable => "NotRecomposable",
            Self::NotSafe => "NotSafe",
            Self::NotSound => "NotSound",
            Self::SoundnessUndecided => "SoundnessUndecided",
        }
    }

    /// The case's documented meaning, from the graph.
    pub fn doc(&self) -> &'static str {
        match self {
            Self::IrreducibleFragment => "No base case and no valid partition -- Algorithm 3 line 25's FallThrough.",
            Self::BudgetExhausted => "The bounded recursion budget ran out before termination.",
            Self::BoundedLanguageAgreementFailed => "The two independently-computed languages disagreed at the checked bound. NOT Theorem 5.5, which quantifies over the whole language.",
            Self::InternalNetConstruction => "A projection produced a sub-net failing WfNet::new -- algorithm-internal, surfaced as a refusal rather than a panic.",
            Self::VacuousLanguageBound => "A bound of 0 compares two empty sets. Both enumerators return the empty language there, so they agree vacuously -- independence of implementation does not imply independence of failure mode.",
            Self::NotRecomposable => "The model has no language-preserving WF-net image -- e.g. a bounded DoRedo, which an unbounded net cycle would widen.",
            Self::NotSafe => "Some reachable marking carries more than one token in a place. Lemmas 5.1-5.4 assume a safe net, so Algorithm 3 would return a model with no proof attached.",
            Self::NotSound => "At least one of van der Aalst's three clauses fails: option-to-complete, proper completion, no dead transitions.",
            Self::SoundnessUndecided => "The reachability graph exceeded MAX_REACHABLE_MARKINGS before the token game terminated. Undecided, not decided favourably.",
        }
    }
}
/// PDDL 3.0 trajectory constraint forms. A monitor that cannot decide a form must refuse at admission, never no-op.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum TrajectoryConstraint {
    /// Holds in every state.
    Always,
    /// Holds in at least one state.
    Sometime,
    /// Holds in at most one contiguous interval.
    AtMostOnce,
    /// (sometime-before phi psi): psi must hold strictly before any occurrence of phi. The FIRST argument is the triggered/later condition.
    SometimeBefore,
    /// (sometime-after phi psi): for all i, phi@i implies exists j>=i with psi@j.
    SometimeAfter,
    /// Deadline over a timed trajectory.
    Within,
    /// Deadline following every trigger.
    AlwaysWithin,
    /// Holds across a bounded time window.
    HoldDuring,
    /// Holds from a time point onward.
    HoldAfter,
    /// Conjunction; must be flattened before monitor construction.
    And,
}

impl TrajectoryConstraint {
    /// Every case, in declared order.
    pub const ALL: &'static [Self] = &[
        Self::Always,
        Self::Sometime,
        Self::AtMostOnce,
        Self::SometimeBefore,
        Self::SometimeAfter,
        Self::Within,
        Self::AlwaysWithin,
        Self::HoldDuring,
        Self::HoldAfter,
        Self::And,
    ];

    /// The case's name as written in the graph.
    pub fn name(&self) -> &'static str {
        match self {
            Self::Always => "Always",
            Self::Sometime => "Sometime",
            Self::AtMostOnce => "AtMostOnce",
            Self::SometimeBefore => "SometimeBefore",
            Self::SometimeAfter => "SometimeAfter",
            Self::Within => "Within",
            Self::AlwaysWithin => "AlwaysWithin",
            Self::HoldDuring => "HoldDuring",
            Self::HoldAfter => "HoldAfter",
            Self::And => "And",
        }
    }

    /// The case's documented meaning, from the graph.
    pub fn doc(&self) -> &'static str {
        match self {
            Self::Always => "Holds in every state.",
            Self::Sometime => "Holds in at least one state.",
            Self::AtMostOnce => "Holds in at most one contiguous interval.",
            Self::SometimeBefore => "(sometime-before phi psi): psi must hold strictly before any occurrence of phi. The FIRST argument is the triggered/later condition.",
            Self::SometimeAfter => "(sometime-after phi psi): for all i, phi@i implies exists j>=i with psi@j.",
            Self::Within => "Deadline over a timed trajectory.",
            Self::AlwaysWithin => "Deadline following every trigger.",
            Self::HoldDuring => "Holds across a bounded time window.",
            Self::HoldAfter => "Holds from a time point onward.",
            Self::And => "Conjunction; must be flattened before monitor construction.",
        }
    }
}
