// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/chains.ttl
// Regenerate: `ggen sync`. Declares the 8 JTBD chain test modules.

pub mod anticheat_verdict;
pub mod audio_cascade;
pub mod combat_hit;
pub mod mp_resync;
pub mod nav_quest;
pub mod procgen_tile;
pub mod quality_loop;
pub mod shop_purchase;
