// GENERATED BY ggen — DO NOT EDIT. Source: ggen/schema/chains.ttl
// Regenerate: `ggen sync`. Declares the 8 JTBD chain test modules.
// COVERAGE: complements corpus.rs (all 75 kernels) with integration paths —
// corpus.rs is the portability oracle (frozen digest), chain tests are the
// composition oracle (non-determinism + cross-kernel data-flow correctness).

pub mod anticheat_verdict;
pub mod audio_cascade;
pub mod combat_hit;
pub mod mp_resync;
pub mod nav_quest;
pub mod procgen_tile;
pub mod quality_loop;
pub mod shop_purchase;
