// GENERATED by `ggen sync` from ontology/bcinr.ttl -- DO NOT EDIT.
//
// Arity side conditions projected from the source of record. `powl2.rs`
// previously checked only `is_empty()`, admitting one-child models the paper
// does not define, while `PaperPOWL2.lean:145,148` carried the bound as a
// proof obligation. One fact, two projections that disagreed.

/// Minimum children for `Powl2Model::ChoiceGraph`.
///
/// Def 3.7 (POWL Model) states `n >= 2`.
pub const CHOICE_GRAPH_MIN_CHILDREN: usize = 2;

/// Minimum children for `Powl2Model::PartialOrder`.
///
/// Def 3.7 (POWL Model) states `n >= 2`.
pub const PARTIAL_ORDER_MIN_CHILDREN: usize = 2;
