//! bcinr-powl — Partially Ordered Workflow Language runtime for bcinr.
//!
//! # Nightly features
//!
//! - `adt_const_params`: allows [`crate::typestate::TopologyKind`] as a const
//!   generic parameter.
//! - `generic_const_exprs`: enables `[u64; N]` in const generic position,
//!   unlocking compile-time topology encoding in [`const_scheduler`] and
//!   512-op wide tapes in [`scheduler_wide`].
//!
//! The recursive POWL 2.0 model is defined in [`powl2`]. Both hand-authored
//! POWL 2.0 and planner-output POWL v2 compile to an executable v2 tape;
//! neither requires conversion through the legacy scheduler representation.
#![feature(adt_const_params)]
#![feature(generic_const_exprs)]
#![allow(incomplete_features)] // generic_const_exprs is still being stabilised

pub mod ocel;
pub use ocel::ConformanceResult;
pub mod admit;
pub mod compiler;
pub mod const_scheduler;
pub mod dispatcher;
pub mod enterprise;
/// Arity side conditions generated by `ggen sync` from `ontology/graph.ttl`.
/// Do not hand-edit; edit the graph and regenerate.
pub mod generated_arity;
pub mod language;
pub mod model;
pub mod multifractal;
pub mod powl2;
pub mod process_rewrite;
pub mod process_toolkit;
pub mod projection;
pub mod receipt_worker;
pub mod recompose;
pub mod scheduler;
pub mod scheduler_v2;
pub mod scheduler_wide;
pub mod scheduler_wired;
pub mod tape;
pub mod typestate;
pub mod wf_net;
pub mod wf_to_powl;
