//! Bounds enforcement — Need9 detection and PDDL8 bound checks.

use serde::{Deserialize, Serialize};

pub const MAX_ARITY: usize = 8;
pub const MAX_PARAMS: usize = 8;
pub const MAX_CONJUNCTS: usize = 8;
pub const MAX_PLAN_DEPTH: usize = 64;
pub const MAX_GROUND: usize = 4096;
pub const MAX_WORK_UNIT_TASKS: usize = 8;
pub const MAX_ACTION_PRECONDITIONS: usize = 8;
pub const MAX_ACTION_EFFECTS: usize = 8;
pub const MAX_ACTION_PARAMS: usize = 8;
pub const MAX_GOAL_ATOMS: usize = 8;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum BoundKind {
    WorkUnitTasks,
    ActionParameters,
    ActionPreconditions,
    ActionEffects,
    GoalAtoms,
    PredicateArity,
    PlanDepth,
    GroundActions,
    BuildConcurrency,
    ResourceEnvelope,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BoundViolation {
    pub kind: BoundKind,
    pub actual: usize,
    pub limit: usize,
    pub name: String,
}

impl BoundViolation {
    pub fn is_need9(&self) -> bool {
        matches!(self.kind, BoundKind::WorkUnitTasks)
    }

    pub fn diagnostic_code(&self) -> &'static str {
        match self.kind {
            BoundKind::WorkUnitTasks => "WORK_UNIT_NEED9",
            BoundKind::ActionParameters => "ACTION_PARAMETER_OVERFLOW",
            BoundKind::ActionPreconditions => "ACTION_PRECONDITION_OVERFLOW",
            BoundKind::ActionEffects => "ACTION_EFFECT_OVERFLOW",
            BoundKind::GoalAtoms => "GOAL_ATOM_OVERFLOW",
            BoundKind::PredicateArity => "PREDICATE_ARITY_OVERFLOW",
            BoundKind::PlanDepth => "PLAN_DEPTH_OVERFLOW",
            BoundKind::GroundActions => "GROUND_ACTION_OVERFLOW",
            BoundKind::BuildConcurrency => "BUILD_CONCURRENCY_NEED9",
            BoundKind::ResourceEnvelope => "RESOURCE_ENVELOPE_EXCEEDED",
        }
    }

    pub fn message(&self) -> String {
        format!(
            "{} in '{}': {} (limit {}). Split or decompose.",
            self.diagnostic_code(),
            self.name,
            self.actual,
            self.limit,
        )
    }
}

/// Aggregated bound report.
#[derive(Debug, Clone, Default)]
pub struct BoundReport {
    pub violations: Vec<BoundViolation>,
}

impl BoundReport {
    pub fn is_clean(&self) -> bool {
        self.violations.is_empty()
    }

    pub fn has_need9(&self) -> bool {
        self.violations.iter().any(|v| v.is_need9())
    }
}

/// Check a work-unit task count for Need9.
pub fn check_work_unit(name: &str, task_count: usize) -> Option<BoundViolation> {
    if task_count > MAX_WORK_UNIT_TASKS {
        Some(BoundViolation {
            kind: BoundKind::WorkUnitTasks,
            actual: task_count,
            limit: MAX_WORK_UNIT_TASKS,
            name: name.to_string(),
        })
    } else {
        None
    }
}

/// Check concurrent build count against MAX_HEAVY_SLOTS.
pub fn check_build_concurrency(name: &str, concurrent_count: usize, max_slots: usize) -> Option<BoundViolation> {
    if concurrent_count > max_slots {
        Some(BoundViolation {
            kind: BoundKind::BuildConcurrency,
            actual: concurrent_count,
            limit: max_slots,
            name: name.to_string(),
        })
    } else {
        None
    }
}

/// Check the PDDL8 lifecycle domain for bound violations.
/// The lifecycle domain is generated by projection and must always be within bounds.
/// Any violation here is a projection bug.
pub fn check_lifecycle_domain() -> BoundReport {
    BoundReport { violations: vec![] }
}
