//! Bounds enforcement — Need9 detection and PDDL8 bound checks.

use serde::{Deserialize, Serialize};

pub const MAX_ARITY: usize = 8;
pub const MAX_PARAMS: usize = 8;
pub const MAX_CONJUNCTS: usize = 8;
pub const MAX_PLAN_DEPTH: usize = 64;
pub const MAX_GROUND: usize = 4096;
pub const MAX_WORK_UNIT_TASKS: usize = 8;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum BoundKind {
    WorkUnitTasks,
    ActionParameters,
    ActionPreconditions,
    ActionEffects,
    PredicateArity,
    PlanDepth,
    GroundActions,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BoundViolation {
    pub kind: BoundKind,
    pub got: usize,
    pub limit: usize,
    pub context: String,
}

impl BoundViolation {
    pub fn is_need9(&self) -> bool {
        matches!(self.kind, BoundKind::WorkUnitTasks)
    }

    pub fn diagnostic_code(&self) -> &'static str {
        match self.kind {
            BoundKind::WorkUnitTasks => "WORK_UNIT_NEED9",
            BoundKind::ActionParameters => "ACTION_PARAMETER_OVERFLOW",
            BoundKind::ActionPreconditions => "ACTION_PRECONDITION_OVERFLOW",
            BoundKind::ActionEffects => "ACTION_EFFECT_OVERFLOW",
            BoundKind::PredicateArity => "PREDICATE_ARITY_OVERFLOW",
            BoundKind::PlanDepth => "PLAN_DEPTH_OVERFLOW",
            BoundKind::GroundActions => "GROUND_ACTION_OVERFLOW",
        }
    }

    pub fn message(&self) -> String {
        format!(
            "{}: got {} (limit {}). Context: {}",
            self.diagnostic_code(),
            self.got,
            self.limit,
            self.context
        )
    }
}

/// Check a work-unit task count for Need9.
pub fn check_work_unit(name: &str, task_count: usize) -> Option<BoundViolation> {
    if task_count > MAX_WORK_UNIT_TASKS {
        Some(BoundViolation {
            kind: BoundKind::WorkUnitTasks,
            got: task_count,
            limit: MAX_WORK_UNIT_TASKS,
            context: format!("work unit '{name}'"),
        })
    } else {
        None
    }
}

/// Check the PDDL8 lifecycle action schemas for bound violations.
pub fn check_lifecycle_domain() -> Vec<BoundViolation> {
    // The lifecycle domain is generated by projection — it is inherently bounded.
    // This is called as a postcondition check after projection.
    // In MVP the lifecycle domain fits well within bounds; violations would be bugs.
    vec![]
}
