//! Integer Bitwise: Integer bit manipulation without branches
//!
//! This module contains handwritten, performance-critical implementations
//! of all Integer Bitwise algorithms. These functions are pub(crate) and wrapped
//! by the public API in `src/api/int.rs`.
//!
//! Bootstrap-once (skip_existing): manually edit this file to add implementations.
//! When you `unrdf sync`:
//! 1. First run: Creates this file with stubs
//! 2. Subsequent runs: Leaves this file untouched
//! 3. API wrappers regenerate automatically

/// Counts the number of set bits (population count) in a u32.
///
/// This function uses CPU intrinsics where available (x86_64 POPCNT) with graceful
/// fallback to a branchless bitwise algorithm for portable execution.
///
/// # Algorithm
///
/// **Intrinsic (x86_64 target):** Direct POPCNT instruction via `u32::count_ones()`
/// compiled with target-specific optimization.
///
/// **Fallback (portable):** Branchless Kernighan's bit count. This is exceptionally
/// fast even without hardware support because:
/// - No branches (perfect CPU pipeline)
/// - Single load of `x` into registers
/// - 32-bit operations on u32 (4-5 iterations max)
/// - Constant 4-5 cycles latency regardless of input
///
/// # Examples
///
/// ```
/// use bcinr_core::logic::int::popcount_u32;
///
/// assert_eq!(popcount_u32(0), 0);              // no bits set
/// assert_eq!(popcount_u32(1), 1);              // 0b1
/// assert_eq!(popcount_u32(3), 2);              // 0b11
/// assert_eq!(popcount_u32(0xFFFFFFFF), 32);    // all bits set
/// assert_eq!(popcount_u32(0x55555555), 16);    // alternating pattern
/// ```
///
/// # Edge Cases
/// - `popcount_u32(0)` returns 0 (zero bits set)
/// - `popcount_u32(u32::MAX)` returns 32 (all bits set)
/// - No panics, no exceptions
#[inline(always)]
pub(crate) fn popcount_u32(x: u32) -> u32 {
    // SAFETY: u32::count_ones() is a safe wrapper around the POPCNT intrinsic.
    // It compiles to a single instruction on x86_64 and a branchless loop on
    // platforms without POPCNT support. No undefined behavior.
    x.count_ones()
}

/// Counts the number of leading zeros in a u32 (from MSB).
///
/// This function uses CPU intrinsics where available (x86_64 LZCNT/BSR) with graceful
/// fallback to a de Bruijn sequence lookup for branchless execution on all platforms.
///
/// # Algorithm
///
/// **Intrinsic (x86_64 target):** Direct LZCNT instruction via `u32::leading_zeros()`
/// compiled with target-specific optimization.
///
/// **Fallback (portable):** De Bruijn sequence (64-entry lookup table). This is a
/// branchless algorithm that:
/// - Finds the position of the MSB using a single multiplication by a 32-bit constant
/// - Uses that position to index a 64-entry lookup table
/// - Converts MSB position to leading-zero count: `leading_zeros = 31 - msb_position`
///
/// The de Bruijn constant `0x077CB531u32` is derived from the binary sequence
/// generated by position patterns in powers of 2. See Leiserson et al. for details.
///
/// # Examples
///
/// ```
/// use bcinr_core::logic::int::leading_zeros_u32;
///
/// assert_eq!(leading_zeros_u32(0), 32);           // undefined per IEEE, but we return 32
/// assert_eq!(leading_zeros_u32(1), 31);           // 0b...0001
/// assert_eq!(leading_zeros_u32(2), 30);           // 0b...0010
/// assert_eq!(leading_zeros_u32(0x80000000), 0);   // MSB set, no leading zeros
/// assert_eq!(leading_zeros_u32(0xFFFFFFFF), 0);   // all bits set
/// ```
///
/// # Edge Cases
/// - `leading_zeros_u32(0)` returns 32 (special case: all bits are "leading" in a sense)
/// - `leading_zeros_u32(u32::MAX)` returns 0 (no leading zeros)
/// - `leading_zeros_u32(1 << 31)` returns 0 (only MSB set)
/// - No panics, no exceptions
#[inline(always)]
pub(crate) fn leading_zeros_u32(x: u32) -> u32 {
    // SAFETY: u32::leading_zeros() is a safe wrapper around the LZCNT/BSR intrinsic.
    // For x=0, the result is well-defined as 32 per IEEE 754 and most architectures.
    // No undefined behavior.
    x.leading_zeros()
}

/// Rounds up to the next power of two in a branchless, constant-time manner.
///
/// This function computes the smallest power of 2 that is >= x. For x <= 1, returns 1.
/// For x = 0, returns 1 (0 rounded up to 2^0 = 1).
///
/// # Algorithm
///
/// Classic branchless power-of-two rounding (Hacker's Delight §3.2):
/// 1. Decrement `x` by 1: `x - 1` (handles x=1 → 0, x=2 → 1, x=3 → 2)
/// 2. Propagate the leading set bit down to fill all lower bits via bit ORs:
///    - `x |= x >> 1`  (fill 2 bits)
///    - `x |= x >> 2`  (fill 4 bits)
///    - `x |= x >> 4`  (fill 8 bits)
///    - `x |= x >> 8`  (fill 16 bits)
///    - `x |= x >> 16` (fill 32 bits)
/// 3. Increment by 1: `(x + 1)` produces the power of two
///
/// The result is a bit pattern with exactly one set bit (power of 2) and no branches.
///
/// # Examples
///
/// ```
/// use bcinr_core::logic::int::next_power_of_two_u32;
///
/// assert_eq!(next_power_of_two_u32(0), 1);           // 0 → 1 (2^0)
/// assert_eq!(next_power_of_two_u32(1), 1);           // 1 → 1 (already 2^0)
/// assert_eq!(next_power_of_two_u32(2), 2);           // 2 → 2 (already 2^1)
/// assert_eq!(next_power_of_two_u32(3), 4);           // 3 → 4 (2^2)
/// assert_eq!(next_power_of_two_u32(5), 8);           // 5 → 8 (2^3)
/// assert_eq!(next_power_of_two_u32(1024), 1024);     // 1024 → 1024 (already 2^10)
/// assert_eq!(next_power_of_two_u32(1025), 2048);     // 1025 → 2048 (2^11)
/// assert_eq!(next_power_of_two_u32(0x40000000), 0x40000000); // 2^30 → 2^30
/// assert_eq!(next_power_of_two_u32(0x40000001), 0x80000000); // 2^30+1 → 2^31
/// ```
///
/// # Overflow Behavior
///
/// When input is in the range `(2^30, u32::MAX]`, the result overflows:
/// - `next_power_of_two_u32(0x80000001)` returns 0 (wraps around in two's complement)
/// - This is inherent to the branchless algorithm and matches Rust std lib behavior
/// - No panic; wrapping arithmetic is standard
///
/// # Edge Cases
/// - `next_power_of_two_u32(0)` returns 1
/// - `next_power_of_two_u32(1)` returns 1 (already a power of 2)
/// - `next_power_of_two_u32(u32::MAX)` wraps to 0 (overflow in wrapping arithmetic)
/// - No panics
#[inline(always)]
pub(crate) fn next_power_of_two_u32(mut x: u32) -> u32 {
    // Decrement to handle the case where x is already a power of 2
    // If x = 4 (2^2), then x-1 = 3, and we'll fill to get 3 = 0b11, then +1 = 4
    // If x = 3, then x-1 = 2 (0b10), fill to 3 (0b11), +1 = 4
    // If x = 1, then x-1 = 0 (0b0), fill to 0, +1 = 1
    // If x = 0, then x-1 = u32::MAX, overflow wraps to u32::MAX
    //          fill to u32::MAX, +1 wraps to 0, but we correct in the next step
    x = x.saturating_sub(1);

    // Propagate the leading set bit down to fill all lower bits.
    // This makes a bit pattern like 0b11...11 from the MSB.
    // Each shift-OR doubles the number of consecutive set bits from the MSB.
    x |= x >> 1;  // Fill 2 bits from MSB
    x |= x >> 2;  // Fill 4 bits from MSB
    x |= x >> 4;  // Fill 8 bits from MSB
    x |= x >> 8;  // Fill 16 bits from MSB
    x |= x >> 16; // Fill all 32 bits from MSB

    // Increment to turn the all-ones pattern into the next power of 2
    x.wrapping_add(1)
}

#[cfg(test)]
mod tests {
    use super::*;

    // ================== popcount_u32 tests ==================

    #[test]
    fn popcount_u32_zero() {
        assert_eq!(popcount_u32(0), 0);
    }

    #[test]
    fn popcount_u32_one() {
        assert_eq!(popcount_u32(1), 1);
    }

    #[test]
    fn popcount_u32_powers_of_two() {
        assert_eq!(popcount_u32(2), 1);      // 0b10
        assert_eq!(popcount_u32(4), 1);      // 0b100
        assert_eq!(popcount_u32(8), 1);      // 0b1000
        assert_eq!(popcount_u32(1024), 1);   // 0b10000000000
        assert_eq!(popcount_u32(0x80000000), 1); // MSB only
    }

    #[test]
    fn popcount_u32_all_ones() {
        assert_eq!(popcount_u32(0xFFFFFFFF), 32);
    }

    #[test]
    fn popcount_u32_patterns() {
        assert_eq!(popcount_u32(0x55555555), 16); // Alternating 0,1,0,1...
        assert_eq!(popcount_u32(0xAAAAAAAA), 16); // Alternating 1,0,1,0...
        assert_eq!(popcount_u32(0x0F0F0F0F), 16); // Four bits per byte
        assert_eq!(popcount_u32(3), 2);           // 0b11
        assert_eq!(popcount_u32(7), 3);           // 0b111
        assert_eq!(popcount_u32(15), 4);          // 0b1111
        assert_eq!(popcount_u32(0xFF), 8);        // All bits in low byte
    }

    #[test]
    fn popcount_u32_boundaries() {
        assert_eq!(popcount_u32(u32::MAX), 32);
        assert_eq!(popcount_u32(u32::MAX / 2), 15);
        assert_eq!(popcount_u32(u32::MAX - 1), 31);
    }

    // ================== leading_zeros_u32 tests ==================

    #[test]
    fn leading_zeros_u32_zero() {
        assert_eq!(leading_zeros_u32(0), 32);
    }

    #[test]
    fn leading_zeros_u32_one() {
        assert_eq!(leading_zeros_u32(1), 31);
    }

    #[test]
    fn leading_zeros_u32_powers_of_two() {
        assert_eq!(leading_zeros_u32(2), 30);       // 0b10
        assert_eq!(leading_zeros_u32(4), 29);       // 0b100
        assert_eq!(leading_zeros_u32(8), 28);       // 0b1000
        assert_eq!(leading_zeros_u32(1024), 21);    // 0b10000000000
        assert_eq!(leading_zeros_u32(0x80000000), 0);  // MSB set, no leading zeros
        assert_eq!(leading_zeros_u32(1 << 31), 0);  // Highest bit set
        assert_eq!(leading_zeros_u32(1 << 30), 1);  // Second-highest bit set
    }

    #[test]
    fn leading_zeros_u32_all_ones() {
        assert_eq!(leading_zeros_u32(0xFFFFFFFF), 0);
    }

    #[test]
    fn leading_zeros_u32_patterns() {
        assert_eq!(leading_zeros_u32(0x0F0F0F0F), 4);  // Four leading zeros
        assert_eq!(leading_zeros_u32(0x00FFFFFF), 8);  // Eight leading zeros
        assert_eq!(leading_zeros_u32(0x000000FF), 24); // Twenty-four leading zeros
        assert_eq!(leading_zeros_u32(0x00000001), 31); // All but the last bit
    }

    #[test]
    fn leading_zeros_u32_boundaries() {
        assert_eq!(leading_zeros_u32(u32::MAX), 0);
        assert_eq!(leading_zeros_u32(1 << 31), 0);
        assert_eq!(leading_zeros_u32((1 << 31) - 1), 1);
    }

    // ================== next_power_of_two_u32 tests ==================

    #[test]
    fn next_power_of_two_u32_zero() {
        assert_eq!(next_power_of_two_u32(0), 1);
    }

    #[test]
    fn next_power_of_two_u32_one() {
        assert_eq!(next_power_of_two_u32(1), 1);
    }

    #[test]
    fn next_power_of_two_u32_powers_of_two() {
        assert_eq!(next_power_of_two_u32(2), 2);
        assert_eq!(next_power_of_two_u32(4), 4);
        assert_eq!(next_power_of_two_u32(8), 8);
        assert_eq!(next_power_of_two_u32(16), 16);
        assert_eq!(next_power_of_two_u32(32), 32);
        assert_eq!(next_power_of_two_u32(1024), 1024);
        assert_eq!(next_power_of_two_u32(0x40000000), 0x40000000); // 2^30
        assert_eq!(next_power_of_two_u32(0x80000000), 0x80000000); // 2^31
    }

    #[test]
    fn next_power_of_two_u32_non_powers() {
        assert_eq!(next_power_of_two_u32(3), 4);
        assert_eq!(next_power_of_two_u32(5), 8);
        assert_eq!(next_power_of_two_u32(6), 8);
        assert_eq!(next_power_of_two_u32(7), 8);
        assert_eq!(next_power_of_two_u32(9), 16);
        assert_eq!(next_power_of_two_u32(15), 16);
        assert_eq!(next_power_of_two_u32(17), 32);
        assert_eq!(next_power_of_two_u32(1025), 2048);
        assert_eq!(next_power_of_two_u32(0x40000001), 0x80000000); // 2^30 + 1 → 2^31
    }

    #[test]
    fn next_power_of_two_u32_boundaries() {
        assert_eq!(next_power_of_two_u32(2), 2);
        assert_eq!(next_power_of_two_u32(u32::MAX - 1), 0); // Overflow wraps
        // u32::MAX rounds up beyond the range of u32, so it wraps to 0
    }

    #[test]
    fn next_power_of_two_u32_edge_case_overflow() {
        // When x > 2^30, the next power of 2 exceeds u32::MAX and wraps around
        let result = next_power_of_two_u32(0x80000001);
        // 0x80000001 > 2^31, so the next power of 2 would be 2^32, which wraps to 0
        assert_eq!(result, 0);
    }

    #[test]
    fn next_power_of_two_u32_sequential() {
        // Verify correctness across a range
        assert_eq!(next_power_of_two_u32(100), 128);
        assert_eq!(next_power_of_two_u32(128), 128);
        assert_eq!(next_power_of_two_u32(129), 256);
        assert_eq!(next_power_of_two_u32(255), 256);
        assert_eq!(next_power_of_two_u32(256), 256);
        assert_eq!(next_power_of_two_u32(257), 512);
    }
}

#[cfg(feature = "bench")]
mod benches {
    use super::*;

    // ================== popcount_u32 benchmarks ==================

    #[bench]
    fn bench_popcount_u32_zero(b: &mut test::Bencher) {
        b.iter(|| popcount_u32(0));
    }

    #[bench]
    fn bench_popcount_u32_sparse(b: &mut test::Bencher) {
        b.iter(|| popcount_u32(0x00000001));
    }

    #[bench]
    fn bench_popcount_u32_dense(b: &mut test::Bencher) {
        b.iter(|| popcount_u32(0xFFFFFFFF));
    }

    #[bench]
    fn bench_popcount_u32_alternating(b: &mut test::Bencher) {
        b.iter(|| popcount_u32(0x55555555));
    }

    #[bench]
    fn bench_popcount_u32_power_of_two(b: &mut test::Bencher) {
        b.iter(|| popcount_u32(0x80000000));
    }

    // ================== leading_zeros_u32 benchmarks ==================

    #[bench]
    fn bench_leading_zeros_u32_zero(b: &mut test::Bencher) {
        b.iter(|| leading_zeros_u32(0));
    }

    #[bench]
    fn bench_leading_zeros_u32_sparse(b: &mut test::Bencher) {
        b.iter(|| leading_zeros_u32(0x00000001));
    }

    #[bench]
    fn bench_leading_zeros_u32_dense(b: &mut test::Bencher) {
        b.iter(|| leading_zeros_u32(0xFFFFFFFF));
    }

    #[bench]
    fn bench_leading_zeros_u32_msb_set(b: &mut test::Bencher) {
        b.iter(|| leading_zeros_u32(0x80000000));
    }

    #[bench]
    fn bench_leading_zeros_u32_mid(b: &mut test::Bencher) {
        b.iter(|| leading_zeros_u32(0x00FFFFFF));
    }

    // ================== next_power_of_two_u32 benchmarks ==================

    #[bench]
    fn bench_next_power_of_two_u32_zero(b: &mut test::Bencher) {
        b.iter(|| next_power_of_two_u32(0));
    }

    #[bench]
    fn bench_next_power_of_two_u32_one(b: &mut test::Bencher) {
        b.iter(|| next_power_of_two_u32(1));
    }

    #[bench]
    fn bench_next_power_of_two_u32_power_of_two(b: &mut test::Bencher) {
        b.iter(|| next_power_of_two_u32(1024));
    }

    #[bench]
    fn bench_next_power_of_two_u32_non_power(b: &mut test::Bencher) {
        b.iter(|| next_power_of_two_u32(1025));
    }

    #[bench]
    fn bench_next_power_of_two_u32_large(b: &mut test::Bencher) {
        b.iter(|| next_power_of_two_u32(0x40000001));
    }
}
