---
to: "crates/unibit-l1/src/lib.rs"
---
#![no_std]
#![deny(missing_docs)]
#![deny(unsafe_op_in_unsafe_fn)]
#![deny(clippy::unwrap_used)]
#![deny(clippy::expect_used)]

//! # 
//! Generated by unrdf from ontology.